/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface IIAFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "deployIA" | "deployedByFactory"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ImplementationAuthorityDeployed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deployIA",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedByFactory",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "deployIA", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployedByFactory",
    data: BytesLike
  ): Result;
}

export namespace ImplementationAuthorityDeployedEvent {
  export type InputTuple = [_ia: AddressLike];
  export type OutputTuple = [_ia: string];
  export interface OutputObject {
    _ia: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IIAFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IIAFactory;
  waitForDeployment(): Promise<this>;

  interface: IIAFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deployIA: TypedContractMethod<[_token: AddressLike], [string], "nonpayable">;

  deployedByFactory: TypedContractMethod<[_ia: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deployIA"
  ): TypedContractMethod<[_token: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "deployedByFactory"
  ): TypedContractMethod<[_ia: AddressLike], [boolean], "view">;

  getEvent(
    key: "ImplementationAuthorityDeployed"
  ): TypedContractEvent<
    ImplementationAuthorityDeployedEvent.InputTuple,
    ImplementationAuthorityDeployedEvent.OutputTuple,
    ImplementationAuthorityDeployedEvent.OutputObject
  >;

  filters: {
    "ImplementationAuthorityDeployed(address)": TypedContractEvent<
      ImplementationAuthorityDeployedEvent.InputTuple,
      ImplementationAuthorityDeployedEvent.OutputTuple,
      ImplementationAuthorityDeployedEvent.OutputObject
    >;
    ImplementationAuthorityDeployed: TypedContractEvent<
      ImplementationAuthorityDeployedEvent.InputTuple,
      ImplementationAuthorityDeployedEvent.OutputTuple,
      ImplementationAuthorityDeployedEvent.OutputObject
    >;
  };
}
