/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export declare namespace ITREXImplementationAuthority {
  export type VersionStruct = {
    major: BigNumberish;
    minor: BigNumberish;
    patch: BigNumberish;
  };

  export type VersionStructOutput = [
    major: bigint,
    minor: bigint,
    patch: bigint
  ] & { major: bigint; minor: bigint; patch: bigint };

  export type TREXContractsStruct = {
    tokenImplementation: AddressLike;
    ctrImplementation: AddressLike;
    irImplementation: AddressLike;
    irsImplementation: AddressLike;
    tirImplementation: AddressLike;
    mcImplementation: AddressLike;
  };

  export type TREXContractsStructOutput = [
    tokenImplementation: string,
    ctrImplementation: string,
    irImplementation: string,
    irsImplementation: string,
    tirImplementation: string,
    mcImplementation: string
  ] & {
    tokenImplementation: string;
    ctrImplementation: string;
    irImplementation: string;
    irsImplementation: string;
    tirImplementation: string;
    mcImplementation: string;
  };
}

export interface TREXImplementationAuthorityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAndUseTREXVersion"
      | "addTREXVersion"
      | "changeImplementationAuthority"
      | "fetchVersion"
      | "getCTRImplementation"
      | "getContracts"
      | "getCurrentVersion"
      | "getIRImplementation"
      | "getIRSImplementation"
      | "getMCImplementation"
      | "getReferenceContract"
      | "getTIRImplementation"
      | "getTREXFactory"
      | "getTokenImplementation"
      | "isReferenceContract"
      | "owner"
      | "renounceOwnership"
      | "setIAFactory"
      | "setTREXFactory"
      | "transferOwnership"
      | "useTREXVersion"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IAFactorySet"
      | "ImplementationAuthorityChanged"
      | "ImplementationAuthoritySet"
      | "OwnershipTransferred"
      | "TREXFactorySet"
      | "TREXVersionAdded"
      | "TREXVersionFetched"
      | "VersionUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAndUseTREXVersion",
    values: [
      ITREXImplementationAuthority.VersionStruct,
      ITREXImplementationAuthority.TREXContractsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addTREXVersion",
    values: [
      ITREXImplementationAuthority.VersionStruct,
      ITREXImplementationAuthority.TREXContractsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "changeImplementationAuthority",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchVersion",
    values: [ITREXImplementationAuthority.VersionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getCTRImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContracts",
    values: [ITREXImplementationAuthority.VersionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIRImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIRSImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMCImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReferenceContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTIRImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTREXFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isReferenceContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setIAFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTREXFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "useTREXVersion",
    values: [ITREXImplementationAuthority.VersionStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAndUseTREXVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addTREXVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeImplementationAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCTRImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIRImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIRSImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMCImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferenceContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTIRImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTREXFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isReferenceContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIAFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTREXFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "useTREXVersion",
    data: BytesLike
  ): Result;
}

export namespace IAFactorySetEvent {
  export type InputTuple = [iaFactory: AddressLike];
  export type OutputTuple = [iaFactory: string];
  export interface OutputObject {
    iaFactory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ImplementationAuthorityChangedEvent {
  export type InputTuple = [
    _token: AddressLike,
    _newImplementationAuthority: AddressLike
  ];
  export type OutputTuple = [
    _token: string,
    _newImplementationAuthority: string
  ];
  export interface OutputObject {
    _token: string;
    _newImplementationAuthority: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ImplementationAuthoritySetEvent {
  export type InputTuple = [referenceStatus: boolean, trexFactory: AddressLike];
  export type OutputTuple = [referenceStatus: boolean, trexFactory: string];
  export interface OutputObject {
    referenceStatus: boolean;
    trexFactory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TREXFactorySetEvent {
  export type InputTuple = [trexFactory: AddressLike];
  export type OutputTuple = [trexFactory: string];
  export interface OutputObject {
    trexFactory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TREXVersionAddedEvent {
  export type InputTuple = [
    version: ITREXImplementationAuthority.VersionStruct,
    trex: ITREXImplementationAuthority.TREXContractsStruct
  ];
  export type OutputTuple = [
    version: ITREXImplementationAuthority.VersionStructOutput,
    trex: ITREXImplementationAuthority.TREXContractsStructOutput
  ];
  export interface OutputObject {
    version: ITREXImplementationAuthority.VersionStructOutput;
    trex: ITREXImplementationAuthority.TREXContractsStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TREXVersionFetchedEvent {
  export type InputTuple = [
    version: ITREXImplementationAuthority.VersionStruct,
    trex: ITREXImplementationAuthority.TREXContractsStruct
  ];
  export type OutputTuple = [
    version: ITREXImplementationAuthority.VersionStructOutput,
    trex: ITREXImplementationAuthority.TREXContractsStructOutput
  ];
  export interface OutputObject {
    version: ITREXImplementationAuthority.VersionStructOutput;
    trex: ITREXImplementationAuthority.TREXContractsStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VersionUpdatedEvent {
  export type InputTuple = [
    version: ITREXImplementationAuthority.VersionStruct
  ];
  export type OutputTuple = [
    version: ITREXImplementationAuthority.VersionStructOutput
  ];
  export interface OutputObject {
    version: ITREXImplementationAuthority.VersionStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TREXImplementationAuthority extends BaseContract {
  connect(runner?: ContractRunner | null): TREXImplementationAuthority;
  waitForDeployment(): Promise<this>;

  interface: TREXImplementationAuthorityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAndUseTREXVersion: TypedContractMethod<
    [
      _version: ITREXImplementationAuthority.VersionStruct,
      _trex: ITREXImplementationAuthority.TREXContractsStruct
    ],
    [void],
    "nonpayable"
  >;

  addTREXVersion: TypedContractMethod<
    [
      _version: ITREXImplementationAuthority.VersionStruct,
      _trex: ITREXImplementationAuthority.TREXContractsStruct
    ],
    [void],
    "nonpayable"
  >;

  changeImplementationAuthority: TypedContractMethod<
    [_token: AddressLike, _newImplementationAuthority: AddressLike],
    [void],
    "nonpayable"
  >;

  fetchVersion: TypedContractMethod<
    [_version: ITREXImplementationAuthority.VersionStruct],
    [void],
    "nonpayable"
  >;

  getCTRImplementation: TypedContractMethod<[], [string], "view">;

  getContracts: TypedContractMethod<
    [_version: ITREXImplementationAuthority.VersionStruct],
    [ITREXImplementationAuthority.TREXContractsStructOutput],
    "view"
  >;

  getCurrentVersion: TypedContractMethod<
    [],
    [ITREXImplementationAuthority.VersionStructOutput],
    "view"
  >;

  getIRImplementation: TypedContractMethod<[], [string], "view">;

  getIRSImplementation: TypedContractMethod<[], [string], "view">;

  getMCImplementation: TypedContractMethod<[], [string], "view">;

  getReferenceContract: TypedContractMethod<[], [string], "view">;

  getTIRImplementation: TypedContractMethod<[], [string], "view">;

  getTREXFactory: TypedContractMethod<[], [string], "view">;

  getTokenImplementation: TypedContractMethod<[], [string], "view">;

  isReferenceContract: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setIAFactory: TypedContractMethod<
    [iaFactory: AddressLike],
    [void],
    "nonpayable"
  >;

  setTREXFactory: TypedContractMethod<
    [trexFactory: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  useTREXVersion: TypedContractMethod<
    [_version: ITREXImplementationAuthority.VersionStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAndUseTREXVersion"
  ): TypedContractMethod<
    [
      _version: ITREXImplementationAuthority.VersionStruct,
      _trex: ITREXImplementationAuthority.TREXContractsStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addTREXVersion"
  ): TypedContractMethod<
    [
      _version: ITREXImplementationAuthority.VersionStruct,
      _trex: ITREXImplementationAuthority.TREXContractsStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changeImplementationAuthority"
  ): TypedContractMethod<
    [_token: AddressLike, _newImplementationAuthority: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fetchVersion"
  ): TypedContractMethod<
    [_version: ITREXImplementationAuthority.VersionStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCTRImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getContracts"
  ): TypedContractMethod<
    [_version: ITREXImplementationAuthority.VersionStruct],
    [ITREXImplementationAuthority.TREXContractsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentVersion"
  ): TypedContractMethod<
    [],
    [ITREXImplementationAuthority.VersionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIRImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getIRSImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMCImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getReferenceContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTIRImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTREXFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTokenImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isReferenceContract"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setIAFactory"
  ): TypedContractMethod<[iaFactory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTREXFactory"
  ): TypedContractMethod<[trexFactory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "useTREXVersion"
  ): TypedContractMethod<
    [_version: ITREXImplementationAuthority.VersionStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "IAFactorySet"
  ): TypedContractEvent<
    IAFactorySetEvent.InputTuple,
    IAFactorySetEvent.OutputTuple,
    IAFactorySetEvent.OutputObject
  >;
  getEvent(
    key: "ImplementationAuthorityChanged"
  ): TypedContractEvent<
    ImplementationAuthorityChangedEvent.InputTuple,
    ImplementationAuthorityChangedEvent.OutputTuple,
    ImplementationAuthorityChangedEvent.OutputObject
  >;
  getEvent(
    key: "ImplementationAuthoritySet"
  ): TypedContractEvent<
    ImplementationAuthoritySetEvent.InputTuple,
    ImplementationAuthoritySetEvent.OutputTuple,
    ImplementationAuthoritySetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TREXFactorySet"
  ): TypedContractEvent<
    TREXFactorySetEvent.InputTuple,
    TREXFactorySetEvent.OutputTuple,
    TREXFactorySetEvent.OutputObject
  >;
  getEvent(
    key: "TREXVersionAdded"
  ): TypedContractEvent<
    TREXVersionAddedEvent.InputTuple,
    TREXVersionAddedEvent.OutputTuple,
    TREXVersionAddedEvent.OutputObject
  >;
  getEvent(
    key: "TREXVersionFetched"
  ): TypedContractEvent<
    TREXVersionFetchedEvent.InputTuple,
    TREXVersionFetchedEvent.OutputTuple,
    TREXVersionFetchedEvent.OutputObject
  >;
  getEvent(
    key: "VersionUpdated"
  ): TypedContractEvent<
    VersionUpdatedEvent.InputTuple,
    VersionUpdatedEvent.OutputTuple,
    VersionUpdatedEvent.OutputObject
  >;

  filters: {
    "IAFactorySet(address)": TypedContractEvent<
      IAFactorySetEvent.InputTuple,
      IAFactorySetEvent.OutputTuple,
      IAFactorySetEvent.OutputObject
    >;
    IAFactorySet: TypedContractEvent<
      IAFactorySetEvent.InputTuple,
      IAFactorySetEvent.OutputTuple,
      IAFactorySetEvent.OutputObject
    >;

    "ImplementationAuthorityChanged(address,address)": TypedContractEvent<
      ImplementationAuthorityChangedEvent.InputTuple,
      ImplementationAuthorityChangedEvent.OutputTuple,
      ImplementationAuthorityChangedEvent.OutputObject
    >;
    ImplementationAuthorityChanged: TypedContractEvent<
      ImplementationAuthorityChangedEvent.InputTuple,
      ImplementationAuthorityChangedEvent.OutputTuple,
      ImplementationAuthorityChangedEvent.OutputObject
    >;

    "ImplementationAuthoritySet(bool,address)": TypedContractEvent<
      ImplementationAuthoritySetEvent.InputTuple,
      ImplementationAuthoritySetEvent.OutputTuple,
      ImplementationAuthoritySetEvent.OutputObject
    >;
    ImplementationAuthoritySet: TypedContractEvent<
      ImplementationAuthoritySetEvent.InputTuple,
      ImplementationAuthoritySetEvent.OutputTuple,
      ImplementationAuthoritySetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TREXFactorySet(address)": TypedContractEvent<
      TREXFactorySetEvent.InputTuple,
      TREXFactorySetEvent.OutputTuple,
      TREXFactorySetEvent.OutputObject
    >;
    TREXFactorySet: TypedContractEvent<
      TREXFactorySetEvent.InputTuple,
      TREXFactorySetEvent.OutputTuple,
      TREXFactorySetEvent.OutputObject
    >;

    "TREXVersionAdded(tuple,tuple)": TypedContractEvent<
      TREXVersionAddedEvent.InputTuple,
      TREXVersionAddedEvent.OutputTuple,
      TREXVersionAddedEvent.OutputObject
    >;
    TREXVersionAdded: TypedContractEvent<
      TREXVersionAddedEvent.InputTuple,
      TREXVersionAddedEvent.OutputTuple,
      TREXVersionAddedEvent.OutputObject
    >;

    "TREXVersionFetched(tuple,tuple)": TypedContractEvent<
      TREXVersionFetchedEvent.InputTuple,
      TREXVersionFetchedEvent.OutputTuple,
      TREXVersionFetchedEvent.OutputObject
    >;
    TREXVersionFetched: TypedContractEvent<
      TREXVersionFetchedEvent.InputTuple,
      TREXVersionFetchedEvent.OutputTuple,
      TREXVersionFetchedEvent.OutputObject
    >;

    "VersionUpdated(tuple)": TypedContractEvent<
      VersionUpdatedEvent.InputTuple,
      VersionUpdatedEvent.OutputTuple,
      VersionUpdatedEvent.OutputObject
    >;
    VersionUpdated: TypedContractEvent<
      VersionUpdatedEvent.InputTuple,
      VersionUpdatedEvent.OutputTuple,
      VersionUpdatedEvent.OutputObject
    >;
  };
}
