/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface IProxyInterface extends Interface {
  getFunction(
    nameOrSignature: "getImplementationAuthority" | "setImplementationAuthority"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ImplementationAuthoritySet"): EventFragment;

  encodeFunctionData(
    functionFragment: "getImplementationAuthority",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setImplementationAuthority",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getImplementationAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setImplementationAuthority",
    data: BytesLike
  ): Result;
}

export namespace ImplementationAuthoritySetEvent {
  export type InputTuple = [_implementationAuthority: AddressLike];
  export type OutputTuple = [_implementationAuthority: string];
  export interface OutputObject {
    _implementationAuthority: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IProxy extends BaseContract {
  connect(runner?: ContractRunner | null): IProxy;
  waitForDeployment(): Promise<this>;

  interface: IProxyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getImplementationAuthority: TypedContractMethod<[], [string], "view">;

  setImplementationAuthority: TypedContractMethod<
    [_newImplementationAuthority: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getImplementationAuthority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setImplementationAuthority"
  ): TypedContractMethod<
    [_newImplementationAuthority: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ImplementationAuthoritySet"
  ): TypedContractEvent<
    ImplementationAuthoritySetEvent.InputTuple,
    ImplementationAuthoritySetEvent.OutputTuple,
    ImplementationAuthoritySetEvent.OutputObject
  >;

  filters: {
    "ImplementationAuthoritySet(address)": TypedContractEvent<
      ImplementationAuthoritySetEvent.InputTuple,
      ImplementationAuthoritySetEvent.OutputTuple,
      ImplementationAuthoritySetEvent.OutputObject
    >;
    ImplementationAuthoritySet: TypedContractEvent<
      ImplementationAuthoritySetEvent.InputTuple,
      ImplementationAuthoritySetEvent.OutputTuple,
      ImplementationAuthoritySetEvent.OutputObject
    >;
  };
}
