/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IIAFactory,
  IIAFactoryInterface,
} from "../../../../../../@erc3643org/erc-3643/contracts/proxy/authority/IIAFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "_ia",
        type: "address",
      },
    ],
    name: "ImplementationAuthorityDeployed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
    ],
    name: "deployIA",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_ia",
        type: "address",
      },
    ],
    name: "deployedByFactory",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IIAFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IIAFactoryInterface {
    return new Interface(_abi) as IIAFactoryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IIAFactory {
    return new Contract(address, _abi, runner) as unknown as IIAFactory;
  }
}
