/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITREXFactory__factory } from "./ITREXFactory__factory";
export { ITREXGateway__factory } from "./ITREXGateway__factory";
export { TREXFactory__factory } from "./TREXFactory__factory";
export { TREXGateway__factory } from "./TREXGateway__factory";
