/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface IdentityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAgent"
      | "batchRegisterIdentity"
      | "contains"
      | "deleteIdentity"
      | "identity"
      | "identityStorage"
      | "init"
      | "investorCountry"
      | "isAgent"
      | "isVerified"
      | "issuersRegistry"
      | "owner"
      | "registerIdentity"
      | "removeAgent"
      | "renounceOwnership"
      | "setClaimTopicsRegistry"
      | "setIdentityRegistryStorage"
      | "setTrustedIssuersRegistry"
      | "topicsRegistry"
      | "transferOwnership"
      | "updateCountry"
      | "updateIdentity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentAdded"
      | "AgentRemoved"
      | "ClaimTopicsRegistrySet"
      | "CountryUpdated"
      | "IdentityRegistered"
      | "IdentityRemoved"
      | "IdentityStorageSet"
      | "IdentityUpdated"
      | "Initialized"
      | "OwnershipTransferred"
      | "TrustedIssuersRegistrySet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchRegisterIdentity",
    values: [AddressLike[], AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "contains",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteIdentity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityStorage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "investorCountry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issuersRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerIdentity",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setClaimTopicsRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIdentityRegistryStorage",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedIssuersRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "topicsRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCountry",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIdentity",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchRegisterIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contains", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "identity", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "identityStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "investorCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issuersRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setClaimTopicsRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIdentityRegistryStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedIssuersRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "topicsRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateIdentity",
    data: BytesLike
  ): Result;
}

export namespace AgentAddedEvent {
  export type InputTuple = [_agent: AddressLike];
  export type OutputTuple = [_agent: string];
  export interface OutputObject {
    _agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRemovedEvent {
  export type InputTuple = [_agent: AddressLike];
  export type OutputTuple = [_agent: string];
  export interface OutputObject {
    _agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimTopicsRegistrySetEvent {
  export type InputTuple = [claimTopicsRegistry: AddressLike];
  export type OutputTuple = [claimTopicsRegistry: string];
  export interface OutputObject {
    claimTopicsRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountryUpdatedEvent {
  export type InputTuple = [
    investorAddress: AddressLike,
    country: BigNumberish
  ];
  export type OutputTuple = [investorAddress: string, country: bigint];
  export interface OutputObject {
    investorAddress: string;
    country: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRegisteredEvent {
  export type InputTuple = [
    investorAddress: AddressLike,
    identity: AddressLike
  ];
  export type OutputTuple = [investorAddress: string, identity: string];
  export interface OutputObject {
    investorAddress: string;
    identity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRemovedEvent {
  export type InputTuple = [
    investorAddress: AddressLike,
    identity: AddressLike
  ];
  export type OutputTuple = [investorAddress: string, identity: string];
  export interface OutputObject {
    investorAddress: string;
    identity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityStorageSetEvent {
  export type InputTuple = [identityStorage: AddressLike];
  export type OutputTuple = [identityStorage: string];
  export interface OutputObject {
    identityStorage: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityUpdatedEvent {
  export type InputTuple = [oldIdentity: AddressLike, newIdentity: AddressLike];
  export type OutputTuple = [oldIdentity: string, newIdentity: string];
  export interface OutputObject {
    oldIdentity: string;
    newIdentity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustedIssuersRegistrySetEvent {
  export type InputTuple = [trustedIssuersRegistry: AddressLike];
  export type OutputTuple = [trustedIssuersRegistry: string];
  export interface OutputObject {
    trustedIssuersRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IdentityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IdentityRegistry;
  waitForDeployment(): Promise<this>;

  interface: IdentityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAgent: TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;

  batchRegisterIdentity: TypedContractMethod<
    [
      _userAddresses: AddressLike[],
      _identities: AddressLike[],
      _countries: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  contains: TypedContractMethod<[_userAddress: AddressLike], [boolean], "view">;

  deleteIdentity: TypedContractMethod<
    [_userAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  identity: TypedContractMethod<[_userAddress: AddressLike], [string], "view">;

  identityStorage: TypedContractMethod<[], [string], "view">;

  init: TypedContractMethod<
    [
      _trustedIssuersRegistry: AddressLike,
      _claimTopicsRegistry: AddressLike,
      _identityStorage: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  investorCountry: TypedContractMethod<
    [_userAddress: AddressLike],
    [bigint],
    "view"
  >;

  isAgent: TypedContractMethod<[_agent: AddressLike], [boolean], "view">;

  isVerified: TypedContractMethod<
    [_userAddress: AddressLike],
    [boolean],
    "view"
  >;

  issuersRegistry: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerIdentity: TypedContractMethod<
    [_userAddress: AddressLike, _identity: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeAgent: TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setClaimTopicsRegistry: TypedContractMethod<
    [_claimTopicsRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  setIdentityRegistryStorage: TypedContractMethod<
    [_identityRegistryStorage: AddressLike],
    [void],
    "nonpayable"
  >;

  setTrustedIssuersRegistry: TypedContractMethod<
    [_trustedIssuersRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  topicsRegistry: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCountry: TypedContractMethod<
    [_userAddress: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateIdentity: TypedContractMethod<
    [_userAddress: AddressLike, _identity: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAgent"
  ): TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchRegisterIdentity"
  ): TypedContractMethod<
    [
      _userAddresses: AddressLike[],
      _identities: AddressLike[],
      _countries: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contains"
  ): TypedContractMethod<[_userAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deleteIdentity"
  ): TypedContractMethod<[_userAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "identity"
  ): TypedContractMethod<[_userAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "identityStorage"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "init"
  ): TypedContractMethod<
    [
      _trustedIssuersRegistry: AddressLike,
      _claimTopicsRegistry: AddressLike,
      _identityStorage: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "investorCountry"
  ): TypedContractMethod<[_userAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAgent"
  ): TypedContractMethod<[_agent: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[_userAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issuersRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerIdentity"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _identity: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeAgent"
  ): TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setClaimTopicsRegistry"
  ): TypedContractMethod<
    [_claimTopicsRegistry: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setIdentityRegistryStorage"
  ): TypedContractMethod<
    [_identityRegistryStorage: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTrustedIssuersRegistry"
  ): TypedContractMethod<
    [_trustedIssuersRegistry: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "topicsRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCountry"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateIdentity"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _identity: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentAdded"
  ): TypedContractEvent<
    AgentAddedEvent.InputTuple,
    AgentAddedEvent.OutputTuple,
    AgentAddedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRemoved"
  ): TypedContractEvent<
    AgentRemovedEvent.InputTuple,
    AgentRemovedEvent.OutputTuple,
    AgentRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimTopicsRegistrySet"
  ): TypedContractEvent<
    ClaimTopicsRegistrySetEvent.InputTuple,
    ClaimTopicsRegistrySetEvent.OutputTuple,
    ClaimTopicsRegistrySetEvent.OutputObject
  >;
  getEvent(
    key: "CountryUpdated"
  ): TypedContractEvent<
    CountryUpdatedEvent.InputTuple,
    CountryUpdatedEvent.OutputTuple,
    CountryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRegistered"
  ): TypedContractEvent<
    IdentityRegisteredEvent.InputTuple,
    IdentityRegisteredEvent.OutputTuple,
    IdentityRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRemoved"
  ): TypedContractEvent<
    IdentityRemovedEvent.InputTuple,
    IdentityRemovedEvent.OutputTuple,
    IdentityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityStorageSet"
  ): TypedContractEvent<
    IdentityStorageSetEvent.InputTuple,
    IdentityStorageSetEvent.OutputTuple,
    IdentityStorageSetEvent.OutputObject
  >;
  getEvent(
    key: "IdentityUpdated"
  ): TypedContractEvent<
    IdentityUpdatedEvent.InputTuple,
    IdentityUpdatedEvent.OutputTuple,
    IdentityUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TrustedIssuersRegistrySet"
  ): TypedContractEvent<
    TrustedIssuersRegistrySetEvent.InputTuple,
    TrustedIssuersRegistrySetEvent.OutputTuple,
    TrustedIssuersRegistrySetEvent.OutputObject
  >;

  filters: {
    "AgentAdded(address)": TypedContractEvent<
      AgentAddedEvent.InputTuple,
      AgentAddedEvent.OutputTuple,
      AgentAddedEvent.OutputObject
    >;
    AgentAdded: TypedContractEvent<
      AgentAddedEvent.InputTuple,
      AgentAddedEvent.OutputTuple,
      AgentAddedEvent.OutputObject
    >;

    "AgentRemoved(address)": TypedContractEvent<
      AgentRemovedEvent.InputTuple,
      AgentRemovedEvent.OutputTuple,
      AgentRemovedEvent.OutputObject
    >;
    AgentRemoved: TypedContractEvent<
      AgentRemovedEvent.InputTuple,
      AgentRemovedEvent.OutputTuple,
      AgentRemovedEvent.OutputObject
    >;

    "ClaimTopicsRegistrySet(address)": TypedContractEvent<
      ClaimTopicsRegistrySetEvent.InputTuple,
      ClaimTopicsRegistrySetEvent.OutputTuple,
      ClaimTopicsRegistrySetEvent.OutputObject
    >;
    ClaimTopicsRegistrySet: TypedContractEvent<
      ClaimTopicsRegistrySetEvent.InputTuple,
      ClaimTopicsRegistrySetEvent.OutputTuple,
      ClaimTopicsRegistrySetEvent.OutputObject
    >;

    "CountryUpdated(address,uint16)": TypedContractEvent<
      CountryUpdatedEvent.InputTuple,
      CountryUpdatedEvent.OutputTuple,
      CountryUpdatedEvent.OutputObject
    >;
    CountryUpdated: TypedContractEvent<
      CountryUpdatedEvent.InputTuple,
      CountryUpdatedEvent.OutputTuple,
      CountryUpdatedEvent.OutputObject
    >;

    "IdentityRegistered(address,address)": TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;
    IdentityRegistered: TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;

    "IdentityRemoved(address,address)": TypedContractEvent<
      IdentityRemovedEvent.InputTuple,
      IdentityRemovedEvent.OutputTuple,
      IdentityRemovedEvent.OutputObject
    >;
    IdentityRemoved: TypedContractEvent<
      IdentityRemovedEvent.InputTuple,
      IdentityRemovedEvent.OutputTuple,
      IdentityRemovedEvent.OutputObject
    >;

    "IdentityStorageSet(address)": TypedContractEvent<
      IdentityStorageSetEvent.InputTuple,
      IdentityStorageSetEvent.OutputTuple,
      IdentityStorageSetEvent.OutputObject
    >;
    IdentityStorageSet: TypedContractEvent<
      IdentityStorageSetEvent.InputTuple,
      IdentityStorageSetEvent.OutputTuple,
      IdentityStorageSetEvent.OutputObject
    >;

    "IdentityUpdated(address,address)": TypedContractEvent<
      IdentityUpdatedEvent.InputTuple,
      IdentityUpdatedEvent.OutputTuple,
      IdentityUpdatedEvent.OutputObject
    >;
    IdentityUpdated: TypedContractEvent<
      IdentityUpdatedEvent.InputTuple,
      IdentityUpdatedEvent.OutputTuple,
      IdentityUpdatedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TrustedIssuersRegistrySet(address)": TypedContractEvent<
      TrustedIssuersRegistrySetEvent.InputTuple,
      TrustedIssuersRegistrySetEvent.OutputTuple,
      TrustedIssuersRegistrySetEvent.OutputObject
    >;
    TrustedIssuersRegistrySet: TypedContractEvent<
      TrustedIssuersRegistrySetEvent.InputTuple,
      TrustedIssuersRegistrySetEvent.OutputTuple,
      TrustedIssuersRegistrySetEvent.OutputObject
    >;
  };
}
