/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface TrustedIssuersRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addTrustedIssuer"
      | "getTrustedIssuerClaimTopics"
      | "getTrustedIssuers"
      | "getTrustedIssuersForClaimTopic"
      | "hasClaimTopic"
      | "init"
      | "isTrustedIssuer"
      | "owner"
      | "removeTrustedIssuer"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateIssuerClaimTopics"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClaimTopicsUpdated"
      | "Initialized"
      | "OwnershipTransferred"
      | "TrustedIssuerAdded"
      | "TrustedIssuerRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addTrustedIssuer",
    values: [AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustedIssuerClaimTopics",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustedIssuers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustedIssuersForClaimTopic",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimTopic",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "init", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isTrustedIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeTrustedIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIssuerClaimTopics",
    values: [AddressLike, BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "addTrustedIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustedIssuerClaimTopics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustedIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustedIssuersForClaimTopic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasClaimTopic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeTrustedIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateIssuerClaimTopics",
    data: BytesLike
  ): Result;
}

export namespace ClaimTopicsUpdatedEvent {
  export type InputTuple = [
    trustedIssuer: AddressLike,
    claimTopics: BigNumberish[]
  ];
  export type OutputTuple = [trustedIssuer: string, claimTopics: bigint[]];
  export interface OutputObject {
    trustedIssuer: string;
    claimTopics: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustedIssuerAddedEvent {
  export type InputTuple = [
    trustedIssuer: AddressLike,
    claimTopics: BigNumberish[]
  ];
  export type OutputTuple = [trustedIssuer: string, claimTopics: bigint[]];
  export interface OutputObject {
    trustedIssuer: string;
    claimTopics: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustedIssuerRemovedEvent {
  export type InputTuple = [trustedIssuer: AddressLike];
  export type OutputTuple = [trustedIssuer: string];
  export interface OutputObject {
    trustedIssuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TrustedIssuersRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): TrustedIssuersRegistry;
  waitForDeployment(): Promise<this>;

  interface: TrustedIssuersRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addTrustedIssuer: TypedContractMethod<
    [_trustedIssuer: AddressLike, _claimTopics: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getTrustedIssuerClaimTopics: TypedContractMethod<
    [_trustedIssuer: AddressLike],
    [bigint[]],
    "view"
  >;

  getTrustedIssuers: TypedContractMethod<[], [string[]], "view">;

  getTrustedIssuersForClaimTopic: TypedContractMethod<
    [claimTopic: BigNumberish],
    [string[]],
    "view"
  >;

  hasClaimTopic: TypedContractMethod<
    [_issuer: AddressLike, _claimTopic: BigNumberish],
    [boolean],
    "view"
  >;

  init: TypedContractMethod<[], [void], "nonpayable">;

  isTrustedIssuer: TypedContractMethod<
    [_issuer: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeTrustedIssuer: TypedContractMethod<
    [_trustedIssuer: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateIssuerClaimTopics: TypedContractMethod<
    [_trustedIssuer: AddressLike, _claimTopics: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addTrustedIssuer"
  ): TypedContractMethod<
    [_trustedIssuer: AddressLike, _claimTopics: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTrustedIssuerClaimTopics"
  ): TypedContractMethod<[_trustedIssuer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTrustedIssuers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTrustedIssuersForClaimTopic"
  ): TypedContractMethod<[claimTopic: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasClaimTopic"
  ): TypedContractMethod<
    [_issuer: AddressLike, _claimTopic: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "init"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isTrustedIssuer"
  ): TypedContractMethod<[_issuer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeTrustedIssuer"
  ): TypedContractMethod<[_trustedIssuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateIssuerClaimTopics"
  ): TypedContractMethod<
    [_trustedIssuer: AddressLike, _claimTopics: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ClaimTopicsUpdated"
  ): TypedContractEvent<
    ClaimTopicsUpdatedEvent.InputTuple,
    ClaimTopicsUpdatedEvent.OutputTuple,
    ClaimTopicsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TrustedIssuerAdded"
  ): TypedContractEvent<
    TrustedIssuerAddedEvent.InputTuple,
    TrustedIssuerAddedEvent.OutputTuple,
    TrustedIssuerAddedEvent.OutputObject
  >;
  getEvent(
    key: "TrustedIssuerRemoved"
  ): TypedContractEvent<
    TrustedIssuerRemovedEvent.InputTuple,
    TrustedIssuerRemovedEvent.OutputTuple,
    TrustedIssuerRemovedEvent.OutputObject
  >;

  filters: {
    "ClaimTopicsUpdated(address,uint256[])": TypedContractEvent<
      ClaimTopicsUpdatedEvent.InputTuple,
      ClaimTopicsUpdatedEvent.OutputTuple,
      ClaimTopicsUpdatedEvent.OutputObject
    >;
    ClaimTopicsUpdated: TypedContractEvent<
      ClaimTopicsUpdatedEvent.InputTuple,
      ClaimTopicsUpdatedEvent.OutputTuple,
      ClaimTopicsUpdatedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TrustedIssuerAdded(address,uint256[])": TypedContractEvent<
      TrustedIssuerAddedEvent.InputTuple,
      TrustedIssuerAddedEvent.OutputTuple,
      TrustedIssuerAddedEvent.OutputObject
    >;
    TrustedIssuerAdded: TypedContractEvent<
      TrustedIssuerAddedEvent.InputTuple,
      TrustedIssuerAddedEvent.OutputTuple,
      TrustedIssuerAddedEvent.OutputObject
    >;

    "TrustedIssuerRemoved(address)": TypedContractEvent<
      TrustedIssuerRemovedEvent.InputTuple,
      TrustedIssuerRemovedEvent.OutputTuple,
      TrustedIssuerRemovedEvent.OutputObject
    >;
    TrustedIssuerRemoved: TypedContractEvent<
      TrustedIssuerRemovedEvent.InputTuple,
      TrustedIssuerRemovedEvent.OutputTuple,
      TrustedIssuerRemovedEvent.OutputObject
    >;
  };
}
