/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITREXFactory } from "./ITREXFactory";
export type { ITREXGateway } from "./ITREXGateway";
export type { TREXFactory } from "./TREXFactory";
export type { TREXGateway } from "./TREXGateway";
