/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export declare namespace ITREXFactory {
  export type TokenDetailsStruct = {
    owner: AddressLike;
    name: string;
    symbol: string;
    decimals: BigNumberish;
    irs: AddressLike;
    ONCHAINID: AddressLike;
    irAgents: AddressLike[];
    tokenAgents: AddressLike[];
    complianceModules: AddressLike[];
    complianceSettings: BytesLike[];
  };

  export type TokenDetailsStructOutput = [
    owner: string,
    name: string,
    symbol: string,
    decimals: bigint,
    irs: string,
    ONCHAINID: string,
    irAgents: string[],
    tokenAgents: string[],
    complianceModules: string[],
    complianceSettings: string[]
  ] & {
    owner: string;
    name: string;
    symbol: string;
    decimals: bigint;
    irs: string;
    ONCHAINID: string;
    irAgents: string[];
    tokenAgents: string[];
    complianceModules: string[];
    complianceSettings: string[];
  };

  export type ClaimDetailsStruct = {
    claimTopics: BigNumberish[];
    issuers: AddressLike[];
    issuerClaims: BigNumberish[][];
  };

  export type ClaimDetailsStructOutput = [
    claimTopics: bigint[],
    issuers: string[],
    issuerClaims: bigint[][]
  ] & { claimTopics: bigint[]; issuers: string[]; issuerClaims: bigint[][] };
}

export interface ITREXFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deployTREXSuite"
      | "getIdFactory"
      | "getImplementationAuthority"
      | "getToken"
      | "recoverContractOwnership"
      | "setIdFactory"
      | "setImplementationAuthority"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deployed"
      | "IdFactorySet"
      | "ImplementationAuthoritySet"
      | "TREXSuiteDeployed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deployTREXSuite",
    values: [
      string,
      ITREXFactory.TokenDetailsStruct,
      ITREXFactory.ClaimDetailsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getIdFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getImplementationAuthority",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getToken", values: [string]): string;
  encodeFunctionData(
    functionFragment: "recoverContractOwnership",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIdFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setImplementationAuthority",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployTREXSuite",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIdFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImplementationAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recoverContractOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIdFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setImplementationAuthority",
    data: BytesLike
  ): Result;
}

export namespace DeployedEvent {
  export type InputTuple = [_addr: AddressLike];
  export type OutputTuple = [_addr: string];
  export interface OutputObject {
    _addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdFactorySetEvent {
  export type InputTuple = [_idFactory: AddressLike];
  export type OutputTuple = [_idFactory: string];
  export interface OutputObject {
    _idFactory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ImplementationAuthoritySetEvent {
  export type InputTuple = [_implementationAuthority: AddressLike];
  export type OutputTuple = [_implementationAuthority: string];
  export interface OutputObject {
    _implementationAuthority: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TREXSuiteDeployedEvent {
  export type InputTuple = [
    _token: AddressLike,
    _ir: AddressLike,
    _irs: AddressLike,
    _tir: AddressLike,
    _ctr: AddressLike,
    _mc: AddressLike,
    _salt: string
  ];
  export type OutputTuple = [
    _token: string,
    _ir: string,
    _irs: string,
    _tir: string,
    _ctr: string,
    _mc: string,
    _salt: string
  ];
  export interface OutputObject {
    _token: string;
    _ir: string;
    _irs: string;
    _tir: string;
    _ctr: string;
    _mc: string;
    _salt: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ITREXFactory extends BaseContract {
  connect(runner?: ContractRunner | null): ITREXFactory;
  waitForDeployment(): Promise<this>;

  interface: ITREXFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deployTREXSuite: TypedContractMethod<
    [
      _salt: string,
      _tokenDetails: ITREXFactory.TokenDetailsStruct,
      _claimDetails: ITREXFactory.ClaimDetailsStruct
    ],
    [void],
    "nonpayable"
  >;

  getIdFactory: TypedContractMethod<[], [string], "view">;

  getImplementationAuthority: TypedContractMethod<[], [string], "view">;

  getToken: TypedContractMethod<[_salt: string], [string], "view">;

  recoverContractOwnership: TypedContractMethod<
    [_contract: AddressLike, _newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  setIdFactory: TypedContractMethod<
    [_idFactory: AddressLike],
    [void],
    "nonpayable"
  >;

  setImplementationAuthority: TypedContractMethod<
    [_implementationAuthority: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deployTREXSuite"
  ): TypedContractMethod<
    [
      _salt: string,
      _tokenDetails: ITREXFactory.TokenDetailsStruct,
      _claimDetails: ITREXFactory.ClaimDetailsStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getIdFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getImplementationAuthority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getToken"
  ): TypedContractMethod<[_salt: string], [string], "view">;
  getFunction(
    nameOrSignature: "recoverContractOwnership"
  ): TypedContractMethod<
    [_contract: AddressLike, _newOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setIdFactory"
  ): TypedContractMethod<[_idFactory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setImplementationAuthority"
  ): TypedContractMethod<
    [_implementationAuthority: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Deployed"
  ): TypedContractEvent<
    DeployedEvent.InputTuple,
    DeployedEvent.OutputTuple,
    DeployedEvent.OutputObject
  >;
  getEvent(
    key: "IdFactorySet"
  ): TypedContractEvent<
    IdFactorySetEvent.InputTuple,
    IdFactorySetEvent.OutputTuple,
    IdFactorySetEvent.OutputObject
  >;
  getEvent(
    key: "ImplementationAuthoritySet"
  ): TypedContractEvent<
    ImplementationAuthoritySetEvent.InputTuple,
    ImplementationAuthoritySetEvent.OutputTuple,
    ImplementationAuthoritySetEvent.OutputObject
  >;
  getEvent(
    key: "TREXSuiteDeployed"
  ): TypedContractEvent<
    TREXSuiteDeployedEvent.InputTuple,
    TREXSuiteDeployedEvent.OutputTuple,
    TREXSuiteDeployedEvent.OutputObject
  >;

  filters: {
    "Deployed(address)": TypedContractEvent<
      DeployedEvent.InputTuple,
      DeployedEvent.OutputTuple,
      DeployedEvent.OutputObject
    >;
    Deployed: TypedContractEvent<
      DeployedEvent.InputTuple,
      DeployedEvent.OutputTuple,
      DeployedEvent.OutputObject
    >;

    "IdFactorySet(address)": TypedContractEvent<
      IdFactorySetEvent.InputTuple,
      IdFactorySetEvent.OutputTuple,
      IdFactorySetEvent.OutputObject
    >;
    IdFactorySet: TypedContractEvent<
      IdFactorySetEvent.InputTuple,
      IdFactorySetEvent.OutputTuple,
      IdFactorySetEvent.OutputObject
    >;

    "ImplementationAuthoritySet(address)": TypedContractEvent<
      ImplementationAuthoritySetEvent.InputTuple,
      ImplementationAuthoritySetEvent.OutputTuple,
      ImplementationAuthoritySetEvent.OutputObject
    >;
    ImplementationAuthoritySet: TypedContractEvent<
      ImplementationAuthoritySetEvent.InputTuple,
      ImplementationAuthoritySetEvent.OutputTuple,
      ImplementationAuthoritySetEvent.OutputObject
    >;

    "TREXSuiteDeployed(address,address,address,address,address,address,string)": TypedContractEvent<
      TREXSuiteDeployedEvent.InputTuple,
      TREXSuiteDeployedEvent.OutputTuple,
      TREXSuiteDeployedEvent.OutputObject
    >;
    TREXSuiteDeployed: TypedContractEvent<
      TREXSuiteDeployedEvent.InputTuple,
      TREXSuiteDeployedEvent.OutputTuple,
      TREXSuiteDeployedEvent.OutputObject
    >;
  };
}
