/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export declare namespace ITREXFactory {
  export type TokenDetailsStruct = {
    owner: AddressLike;
    name: string;
    symbol: string;
    decimals: BigNumberish;
    irs: AddressLike;
    ONCHAINID: AddressLike;
    irAgents: AddressLike[];
    tokenAgents: AddressLike[];
    complianceModules: AddressLike[];
    complianceSettings: BytesLike[];
  };

  export type TokenDetailsStructOutput = [
    owner: string,
    name: string,
    symbol: string,
    decimals: bigint,
    irs: string,
    ONCHAINID: string,
    irAgents: string[],
    tokenAgents: string[],
    complianceModules: string[],
    complianceSettings: string[]
  ] & {
    owner: string;
    name: string;
    symbol: string;
    decimals: bigint;
    irs: string;
    ONCHAINID: string;
    irAgents: string[];
    tokenAgents: string[];
    complianceModules: string[];
    complianceSettings: string[];
  };

  export type ClaimDetailsStruct = {
    claimTopics: BigNumberish[];
    issuers: AddressLike[];
    issuerClaims: BigNumberish[][];
  };

  export type ClaimDetailsStructOutput = [
    claimTopics: bigint[],
    issuers: string[],
    issuerClaims: bigint[][]
  ] & { claimTopics: bigint[]; issuers: string[]; issuerClaims: bigint[][] };
}

export declare namespace ITREXGateway {
  export type FeeStruct = {
    fee: BigNumberish;
    feeToken: AddressLike;
    feeCollector: AddressLike;
  };

  export type FeeStructOutput = [
    fee: bigint,
    feeToken: string,
    feeCollector: string
  ] & { fee: bigint; feeToken: string; feeCollector: string };
}

export interface TREXGatewayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAgent"
      | "addDeployer"
      | "applyFeeDiscount"
      | "batchAddDeployer"
      | "batchApplyFeeDiscount"
      | "batchDeployTREXSuite"
      | "batchRemoveDeployer"
      | "calculateFee"
      | "deployTREXSuite"
      | "enableDeploymentFee"
      | "getDeploymentFee"
      | "getFactory"
      | "getPublicDeploymentStatus"
      | "isAgent"
      | "isDeployer"
      | "isDeploymentFeeEnabled"
      | "owner"
      | "removeAgent"
      | "removeDeployer"
      | "renounceOwnership"
      | "setDeploymentFee"
      | "setFactory"
      | "setPublicDeploymentStatus"
      | "transferFactoryOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentAdded"
      | "AgentRemoved"
      | "DeployerAdded"
      | "DeployerRemoved"
      | "DeploymentFeeEnabled"
      | "DeploymentFeeSet"
      | "FactorySet"
      | "FeeDiscountApplied"
      | "GatewaySuiteDeploymentProcessed"
      | "OwnershipTransferred"
      | "PublicDeploymentStatusSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addDeployer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "applyFeeDiscount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchAddDeployer",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchApplyFeeDiscount",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchDeployTREXSuite",
    values: [
      ITREXFactory.TokenDetailsStruct[],
      ITREXFactory.ClaimDetailsStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchRemoveDeployer",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateFee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployTREXSuite",
    values: [ITREXFactory.TokenDetailsStruct, ITREXFactory.ClaimDetailsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "enableDeploymentFee",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeploymentFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicDeploymentStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDeployer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDeploymentFeeEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeDeployer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDeploymentFee",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPublicDeploymentStatus",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFactoryOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyFeeDiscount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchAddDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchApplyFeeDiscount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchDeployTREXSuite",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchRemoveDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployTREXSuite",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableDeploymentFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeploymentFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFactory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPublicDeploymentStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isDeployer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDeploymentFeeEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDeploymentFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFactory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPublicDeploymentStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFactoryOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AgentAddedEvent {
  export type InputTuple = [_agent: AddressLike];
  export type OutputTuple = [_agent: string];
  export interface OutputObject {
    _agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRemovedEvent {
  export type InputTuple = [_agent: AddressLike];
  export type OutputTuple = [_agent: string];
  export interface OutputObject {
    _agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeployerAddedEvent {
  export type InputTuple = [deployer: AddressLike];
  export type OutputTuple = [deployer: string];
  export interface OutputObject {
    deployer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeployerRemovedEvent {
  export type InputTuple = [deployer: AddressLike];
  export type OutputTuple = [deployer: string];
  export interface OutputObject {
    deployer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeploymentFeeEnabledEvent {
  export type InputTuple = [isEnabled: boolean];
  export type OutputTuple = [isEnabled: boolean];
  export interface OutputObject {
    isEnabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeploymentFeeSetEvent {
  export type InputTuple = [
    fee: BigNumberish,
    feeToken: AddressLike,
    feeCollector: AddressLike
  ];
  export type OutputTuple = [
    fee: bigint,
    feeToken: string,
    feeCollector: string
  ];
  export interface OutputObject {
    fee: bigint;
    feeToken: string;
    feeCollector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FactorySetEvent {
  export type InputTuple = [factory: AddressLike];
  export type OutputTuple = [factory: string];
  export interface OutputObject {
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeDiscountAppliedEvent {
  export type InputTuple = [deployer: AddressLike, discount: BigNumberish];
  export type OutputTuple = [deployer: string, discount: bigint];
  export interface OutputObject {
    deployer: string;
    discount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GatewaySuiteDeploymentProcessedEvent {
  export type InputTuple = [
    requester: AddressLike,
    intendedOwner: AddressLike,
    feeApplied: BigNumberish
  ];
  export type OutputTuple = [
    requester: string,
    intendedOwner: string,
    feeApplied: bigint
  ];
  export interface OutputObject {
    requester: string;
    intendedOwner: string;
    feeApplied: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicDeploymentStatusSetEvent {
  export type InputTuple = [publicDeploymentStatus: boolean];
  export type OutputTuple = [publicDeploymentStatus: boolean];
  export interface OutputObject {
    publicDeploymentStatus: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TREXGateway extends BaseContract {
  connect(runner?: ContractRunner | null): TREXGateway;
  waitForDeployment(): Promise<this>;

  interface: TREXGatewayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAgent: TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;

  addDeployer: TypedContractMethod<
    [deployer: AddressLike],
    [void],
    "nonpayable"
  >;

  applyFeeDiscount: TypedContractMethod<
    [deployer: AddressLike, discount: BigNumberish],
    [void],
    "nonpayable"
  >;

  batchAddDeployer: TypedContractMethod<
    [deployers: AddressLike[]],
    [void],
    "nonpayable"
  >;

  batchApplyFeeDiscount: TypedContractMethod<
    [deployers: AddressLike[], discounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  batchDeployTREXSuite: TypedContractMethod<
    [
      _tokenDetails: ITREXFactory.TokenDetailsStruct[],
      _claimDetails: ITREXFactory.ClaimDetailsStruct[]
    ],
    [void],
    "nonpayable"
  >;

  batchRemoveDeployer: TypedContractMethod<
    [deployers: AddressLike[]],
    [void],
    "nonpayable"
  >;

  calculateFee: TypedContractMethod<[deployer: AddressLike], [bigint], "view">;

  deployTREXSuite: TypedContractMethod<
    [
      _tokenDetails: ITREXFactory.TokenDetailsStruct,
      _claimDetails: ITREXFactory.ClaimDetailsStruct
    ],
    [void],
    "nonpayable"
  >;

  enableDeploymentFee: TypedContractMethod<
    [_isEnabled: boolean],
    [void],
    "nonpayable"
  >;

  getDeploymentFee: TypedContractMethod<
    [],
    [ITREXGateway.FeeStructOutput],
    "view"
  >;

  getFactory: TypedContractMethod<[], [string], "view">;

  getPublicDeploymentStatus: TypedContractMethod<[], [boolean], "view">;

  isAgent: TypedContractMethod<[_agent: AddressLike], [boolean], "view">;

  isDeployer: TypedContractMethod<[deployer: AddressLike], [boolean], "view">;

  isDeploymentFeeEnabled: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeAgent: TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;

  removeDeployer: TypedContractMethod<
    [deployer: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDeploymentFee: TypedContractMethod<
    [_fee: BigNumberish, _feeToken: AddressLike, _feeCollector: AddressLike],
    [void],
    "nonpayable"
  >;

  setFactory: TypedContractMethod<[factory: AddressLike], [void], "nonpayable">;

  setPublicDeploymentStatus: TypedContractMethod<
    [_isEnabled: boolean],
    [void],
    "nonpayable"
  >;

  transferFactoryOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAgent"
  ): TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addDeployer"
  ): TypedContractMethod<[deployer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "applyFeeDiscount"
  ): TypedContractMethod<
    [deployer: AddressLike, discount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchAddDeployer"
  ): TypedContractMethod<[deployers: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchApplyFeeDiscount"
  ): TypedContractMethod<
    [deployers: AddressLike[], discounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchDeployTREXSuite"
  ): TypedContractMethod<
    [
      _tokenDetails: ITREXFactory.TokenDetailsStruct[],
      _claimDetails: ITREXFactory.ClaimDetailsStruct[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchRemoveDeployer"
  ): TypedContractMethod<[deployers: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateFee"
  ): TypedContractMethod<[deployer: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "deployTREXSuite"
  ): TypedContractMethod<
    [
      _tokenDetails: ITREXFactory.TokenDetailsStruct,
      _claimDetails: ITREXFactory.ClaimDetailsStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enableDeploymentFee"
  ): TypedContractMethod<[_isEnabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDeploymentFee"
  ): TypedContractMethod<[], [ITREXGateway.FeeStructOutput], "view">;
  getFunction(
    nameOrSignature: "getFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPublicDeploymentStatus"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAgent"
  ): TypedContractMethod<[_agent: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isDeployer"
  ): TypedContractMethod<[deployer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isDeploymentFeeEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeAgent"
  ): TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeDeployer"
  ): TypedContractMethod<[deployer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDeploymentFee"
  ): TypedContractMethod<
    [_fee: BigNumberish, _feeToken: AddressLike, _feeCollector: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFactory"
  ): TypedContractMethod<[factory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPublicDeploymentStatus"
  ): TypedContractMethod<[_isEnabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferFactoryOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgentAdded"
  ): TypedContractEvent<
    AgentAddedEvent.InputTuple,
    AgentAddedEvent.OutputTuple,
    AgentAddedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRemoved"
  ): TypedContractEvent<
    AgentRemovedEvent.InputTuple,
    AgentRemovedEvent.OutputTuple,
    AgentRemovedEvent.OutputObject
  >;
  getEvent(
    key: "DeployerAdded"
  ): TypedContractEvent<
    DeployerAddedEvent.InputTuple,
    DeployerAddedEvent.OutputTuple,
    DeployerAddedEvent.OutputObject
  >;
  getEvent(
    key: "DeployerRemoved"
  ): TypedContractEvent<
    DeployerRemovedEvent.InputTuple,
    DeployerRemovedEvent.OutputTuple,
    DeployerRemovedEvent.OutputObject
  >;
  getEvent(
    key: "DeploymentFeeEnabled"
  ): TypedContractEvent<
    DeploymentFeeEnabledEvent.InputTuple,
    DeploymentFeeEnabledEvent.OutputTuple,
    DeploymentFeeEnabledEvent.OutputObject
  >;
  getEvent(
    key: "DeploymentFeeSet"
  ): TypedContractEvent<
    DeploymentFeeSetEvent.InputTuple,
    DeploymentFeeSetEvent.OutputTuple,
    DeploymentFeeSetEvent.OutputObject
  >;
  getEvent(
    key: "FactorySet"
  ): TypedContractEvent<
    FactorySetEvent.InputTuple,
    FactorySetEvent.OutputTuple,
    FactorySetEvent.OutputObject
  >;
  getEvent(
    key: "FeeDiscountApplied"
  ): TypedContractEvent<
    FeeDiscountAppliedEvent.InputTuple,
    FeeDiscountAppliedEvent.OutputTuple,
    FeeDiscountAppliedEvent.OutputObject
  >;
  getEvent(
    key: "GatewaySuiteDeploymentProcessed"
  ): TypedContractEvent<
    GatewaySuiteDeploymentProcessedEvent.InputTuple,
    GatewaySuiteDeploymentProcessedEvent.OutputTuple,
    GatewaySuiteDeploymentProcessedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PublicDeploymentStatusSet"
  ): TypedContractEvent<
    PublicDeploymentStatusSetEvent.InputTuple,
    PublicDeploymentStatusSetEvent.OutputTuple,
    PublicDeploymentStatusSetEvent.OutputObject
  >;

  filters: {
    "AgentAdded(address)": TypedContractEvent<
      AgentAddedEvent.InputTuple,
      AgentAddedEvent.OutputTuple,
      AgentAddedEvent.OutputObject
    >;
    AgentAdded: TypedContractEvent<
      AgentAddedEvent.InputTuple,
      AgentAddedEvent.OutputTuple,
      AgentAddedEvent.OutputObject
    >;

    "AgentRemoved(address)": TypedContractEvent<
      AgentRemovedEvent.InputTuple,
      AgentRemovedEvent.OutputTuple,
      AgentRemovedEvent.OutputObject
    >;
    AgentRemoved: TypedContractEvent<
      AgentRemovedEvent.InputTuple,
      AgentRemovedEvent.OutputTuple,
      AgentRemovedEvent.OutputObject
    >;

    "DeployerAdded(address)": TypedContractEvent<
      DeployerAddedEvent.InputTuple,
      DeployerAddedEvent.OutputTuple,
      DeployerAddedEvent.OutputObject
    >;
    DeployerAdded: TypedContractEvent<
      DeployerAddedEvent.InputTuple,
      DeployerAddedEvent.OutputTuple,
      DeployerAddedEvent.OutputObject
    >;

    "DeployerRemoved(address)": TypedContractEvent<
      DeployerRemovedEvent.InputTuple,
      DeployerRemovedEvent.OutputTuple,
      DeployerRemovedEvent.OutputObject
    >;
    DeployerRemoved: TypedContractEvent<
      DeployerRemovedEvent.InputTuple,
      DeployerRemovedEvent.OutputTuple,
      DeployerRemovedEvent.OutputObject
    >;

    "DeploymentFeeEnabled(bool)": TypedContractEvent<
      DeploymentFeeEnabledEvent.InputTuple,
      DeploymentFeeEnabledEvent.OutputTuple,
      DeploymentFeeEnabledEvent.OutputObject
    >;
    DeploymentFeeEnabled: TypedContractEvent<
      DeploymentFeeEnabledEvent.InputTuple,
      DeploymentFeeEnabledEvent.OutputTuple,
      DeploymentFeeEnabledEvent.OutputObject
    >;

    "DeploymentFeeSet(uint256,address,address)": TypedContractEvent<
      DeploymentFeeSetEvent.InputTuple,
      DeploymentFeeSetEvent.OutputTuple,
      DeploymentFeeSetEvent.OutputObject
    >;
    DeploymentFeeSet: TypedContractEvent<
      DeploymentFeeSetEvent.InputTuple,
      DeploymentFeeSetEvent.OutputTuple,
      DeploymentFeeSetEvent.OutputObject
    >;

    "FactorySet(address)": TypedContractEvent<
      FactorySetEvent.InputTuple,
      FactorySetEvent.OutputTuple,
      FactorySetEvent.OutputObject
    >;
    FactorySet: TypedContractEvent<
      FactorySetEvent.InputTuple,
      FactorySetEvent.OutputTuple,
      FactorySetEvent.OutputObject
    >;

    "FeeDiscountApplied(address,uint16)": TypedContractEvent<
      FeeDiscountAppliedEvent.InputTuple,
      FeeDiscountAppliedEvent.OutputTuple,
      FeeDiscountAppliedEvent.OutputObject
    >;
    FeeDiscountApplied: TypedContractEvent<
      FeeDiscountAppliedEvent.InputTuple,
      FeeDiscountAppliedEvent.OutputTuple,
      FeeDiscountAppliedEvent.OutputObject
    >;

    "GatewaySuiteDeploymentProcessed(address,address,uint256)": TypedContractEvent<
      GatewaySuiteDeploymentProcessedEvent.InputTuple,
      GatewaySuiteDeploymentProcessedEvent.OutputTuple,
      GatewaySuiteDeploymentProcessedEvent.OutputObject
    >;
    GatewaySuiteDeploymentProcessed: TypedContractEvent<
      GatewaySuiteDeploymentProcessedEvent.InputTuple,
      GatewaySuiteDeploymentProcessedEvent.OutputTuple,
      GatewaySuiteDeploymentProcessedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PublicDeploymentStatusSet(bool)": TypedContractEvent<
      PublicDeploymentStatusSetEvent.InputTuple,
      PublicDeploymentStatusSetEvent.OutputTuple,
      PublicDeploymentStatusSetEvent.OutputObject
    >;
    PublicDeploymentStatusSet: TypedContractEvent<
      PublicDeploymentStatusSetEvent.InputTuple,
      PublicDeploymentStatusSetEvent.OutputTuple,
      PublicDeploymentStatusSetEvent.OutputObject
    >;
  };
}
