/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as factory from "./factory";
export * as interface from "./interface";
export * as proxy from "./proxy";
export * as version from "./version";
export { Identity__factory } from "./Identity__factory";
