export const ROUTES = Object.freeze({
  root: '/',
  login: '/login',
  signup: '/signup',
  verifyEmail: '/verify-email',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  dashboard: '/app/dashboard',
  projects: '/app/projects',
  createToken: '/app/tokens/new',
  identity: '/app/identity',
  compliance: '/app/compliance',
  investors: '/app/investors',
  transactions: '/app/transactions',
  corporateActions: '/app/corporate-actions',
  documents: '/app/documents',
  reports: '/app/reports',
  users: '/app/team',
  profile: '/app/profile',
  settings: '/app/settings',
  unauthorized: '/unauthorized',
  forbidden: '/forbidden',
  networkError: '/network-error',
  notFound: '*',
});
