-- T-REX Capital Market Backend schema (MySQL 8+)
-- All application timestamps are generated in UTC. No foreign keys are intentionally defined.

CREATE DATABASE IF NOT EXISTS `trexCapitalMarket`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `trexCapitalMarket`;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS `authToken` (
  `tokenUid` char(36) NOT NULL,
  `userUid` char(36) NOT NULL,
  `tokenType` enum('emailVerification','passwordReset') NOT NULL,
  `tokenHash` char(64) NOT NULL,
  `expiresAt` datetime(3) NOT NULL,
  `usedAt` datetime(3) DEFAULT NULL,
  `revokedAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`tokenUid`),
  UNIQUE KEY `ukAuthTokenHash` (`tokenHash`),
  KEY `idxAuthTokenLookup` (`userUid`,`tokenType`,`expiresAt`,`usedAt`,`revokedAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `blockchainIndexedContract` (
  `indexedContractUid` char(36) NOT NULL,
  `indexerName` varchar(80) NOT NULL,
  `chainId` bigint(20) unsigned NOT NULL,
  `tokenUid` char(36) NOT NULL,
  `contractAddress` varchar(42) NOT NULL,
  `startBlock` bigint(20) unsigned NOT NULL,
  `lastBackfilledBlock` bigint(20) unsigned NOT NULL DEFAULT 0,
  `backfillCompletedAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`indexedContractUid`),
  UNIQUE KEY `ukBlockchainIndexedContract` (`indexerName`,`chainId`,`contractAddress`),
  KEY `idxBlockchainIndexedContractBackfill` (`indexerName`,`chainId`,`lastBackfilledBlock`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `blockchainIndexerCheckpoint` (
  `checkpointUid` char(36) NOT NULL,
  `indexerName` varchar(80) NOT NULL,
  `chainId` bigint(20) unsigned NOT NULL,
  `startBlock` bigint(20) unsigned NOT NULL DEFAULT 0,
  `lastIndexedBlock` bigint(20) unsigned NOT NULL DEFAULT 0,
  `lastIndexedBlockHash` varchar(66) DEFAULT NULL,
  `leaseOwner` varchar(120) DEFAULT NULL,
  `leaseExpiresAt` datetime(3) DEFAULT NULL,
  `lastRunAt` datetime(3) DEFAULT NULL,
  `lastSuccessAt` datetime(3) DEFAULT NULL,
  `lastErrorMessage` varchar(2000) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`checkpointUid`),
  UNIQUE KEY `ukBlockchainIndexerCheckpoint` (`indexerName`,`chainId`),
  KEY `idxBlockchainIndexerLease` (`indexerName`,`chainId`,`leaseExpiresAt`,`isActive`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `blockchainTransaction` (
  `transactionUid` char(36) NOT NULL,
  `chainId` bigint(20) unsigned NOT NULL,
  `tokenUid` char(36) NOT NULL,
  `organizationUid` char(36) NOT NULL,
  `tokenAddress` varchar(42) NOT NULL,
  `controllerAddress` varchar(42) DEFAULT NULL,
  `transactionHash` varchar(66) NOT NULL,
  `blockNumber` bigint(20) unsigned DEFAULT NULL,
  `blockHash` varchar(66) DEFAULT NULL,
  `transactionIndex` int(10) unsigned DEFAULT NULL,
  `logIndex` int(10) unsigned DEFAULT NULL,
  `gasUsed` varchar(78) DEFAULT NULL,
  `effectiveGasPrice` varchar(78) DEFAULT NULL,
  `type` enum('INVEST','TRANSFER','REDEMPTION','USDT_APPROVAL','TOKEN_ISSUE','TOKEN_BURN','PRICE_UPDATE') NOT NULL,
  `executionType` enum('DIRECT','DELEGATED') NOT NULL DEFAULT 'DIRECT',
  `initiatedByUserUid` char(36) DEFAULT NULL,
  `initiatedByWallet` varchar(42) NOT NULL,
  `fromWallet` varchar(42) DEFAULT NULL,
  `toWallet` varchar(42) DEFAULT NULL,
  `tokenAmountRaw` varchar(78) DEFAULT NULL,
  `tokenAmountFormatted` decimal(65,18) DEFAULT NULL,
  `usdtAmountRaw` varchar(78) DEFAULT NULL,
  `usdtAmountFormatted` decimal(65,18) DEFAULT NULL,
  `tokenSymbol` varchar(10) DEFAULT NULL,
  `status` enum('SUBMITTED','CONFIRMED','FAILED','ORPHANED') NOT NULL DEFAULT 'SUBMITTED',
  `confirmationCount` int(10) unsigned NOT NULL DEFAULT 0,
  `blockTimestamp` datetime(3) DEFAULT NULL,
  `confirmedAt` datetime(3) DEFAULT NULL,
  `errorCode` varchar(100) DEFAULT NULL,
  `errorMessage` varchar(2000) DEFAULT NULL,
  `isCanonical` tinyint(1) NOT NULL DEFAULT 1,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`transactionUid`),
  UNIQUE KEY `ukBlockchainTransactionAction` (`chainId`,`transactionHash`,`type`),
  UNIQUE KEY `ukBlockchainTransactionEvent` (`chainId`,`transactionHash`,`logIndex`),
  KEY `idxBlockchainTransactionToken` (`tokenUid`,`status`,`blockNumber`),
  KEY `idxBlockchainTransactionOrganization` (`organizationUid`,`status`,`blockTimestamp`),
  KEY `idxBlockchainTransactionInitiator` (`initiatedByUserUid`,`status`,`blockTimestamp`),
  KEY `idxBlockchainTransactionWallets` (`initiatedByWallet`,`fromWallet`,`toWallet`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `cityMaster` (
  `cityUid` char(36) NOT NULL,
  `countryUid` char(36) NOT NULL,
  `stateUid` char(36) NOT NULL,
  `cityName` varchar(150) NOT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`cityUid`),
  UNIQUE KEY `ukCityMasterName` (`stateUid`,`cityName`),
  KEY `idxCityMasterStateName` (`stateUid`,`cityName`,`isActive`,`isDeleted`),
  KEY `idxCityMasterCountryUid` (`countryUid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `claimTopicMaster` (
  `claimTopicUid` char(36) NOT NULL,
  `claimTopicCode` varchar(80) NOT NULL,
  `claimTopicName` varchar(120) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `value` int(10) unsigned NOT NULL,
  `displayOrder` int(10) unsigned NOT NULL DEFAULT 0,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`claimTopicUid`),
  UNIQUE KEY `ukClaimTopicMasterCode` (`claimTopicCode`),
  UNIQUE KEY `ukClaimTopicMasterValue` (`value`),
  KEY `idxClaimTopicMasterStatus` (`isActive`,`isDeleted`,`displayOrder`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `countryMaster` (
  `countryUid` char(36) NOT NULL,
  `countryCode` char(2) NOT NULL,
  `numericCode` char(3) NOT NULL,
  `countryName` varchar(120) NOT NULL,
  `phoneCode` varchar(20) DEFAULT NULL,
  `currencyCode` char(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`countryUid`),
  UNIQUE KEY `ukCountryMasterCode` (`countryCode`),
  UNIQUE KEY `ukCountryMasterNumericCode` (`numericCode`),
  KEY `idxCountryMasterName` (`countryName`,`isActive`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `documentTypeMaster` (
  `documentTypeUid` char(36) NOT NULL,
  `documentTypeCode` varchar(80) NOT NULL,
  `documentTypeName` varchar(150) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `isRequired` tinyint(1) NOT NULL DEFAULT 0,
  `displayOrder` int(10) unsigned NOT NULL DEFAULT 0,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`documentTypeUid`),
  UNIQUE KEY `ukDocumentTypeMasterCode` (`documentTypeCode`),
  KEY `idxDocumentTypeMasterStatus` (`isRequired`,`isActive`,`isDeleted`,`displayOrder`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `entityTypeMaster` (
  `entityTypeUid` char(36) NOT NULL,
  `entityTypeCode` varchar(50) NOT NULL,
  `entityTypeName` varchar(100) NOT NULL,
  `displayOrder` int(10) unsigned NOT NULL DEFAULT 0,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`entityTypeUid`),
  UNIQUE KEY `ukEntityTypeMasterCode` (`entityTypeCode`),
  KEY `idxEntityTypeMasterStatus` (`isActive`,`isDeleted`,`displayOrder`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `generalSettings` (
  `settingUid` char(36) NOT NULL,
  `settingKey` varchar(120) NOT NULL,
  `settingValue` text NOT NULL,
  `valueType` enum('string','number','boolean','json') NOT NULL DEFAULT 'string',
  `settingGroup` varchar(80) NOT NULL DEFAULT 'application',
  `description` varchar(500) DEFAULT NULL,
  `isPublic` tinyint(1) NOT NULL DEFAULT 0,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`settingUid`),
  UNIQUE KEY `ukGeneralSettingsKey` (`settingKey`),
  KEY `idxGeneralSettingsGroup` (`settingGroup`,`isPublic`,`isActive`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `identityRegistryBlockchainEvent` (
  `registryEventUid` char(36) NOT NULL,
  `chainId` bigint(20) unsigned NOT NULL,
  `identityRegistryAddress` varchar(42) NOT NULL,
  `investorWalletAddress` varchar(42) NOT NULL,
  `investorIdentityAddress` varchar(42) NOT NULL,
  `eventName` enum('IdentityRegistered') NOT NULL,
  `txHash` varchar(66) NOT NULL,
  `blockNumber` bigint(20) unsigned NOT NULL,
  `blockHash` varchar(66) DEFAULT NULL,
  `transactionIndex` int(10) unsigned NOT NULL,
  `logIndex` int(10) unsigned NOT NULL,
  `processingStatus` enum('NEW','MATCHED','UNMATCHED','FAILED') NOT NULL DEFAULT 'NEW',
  `matchedRegistrationUid` char(36) DEFAULT NULL,
  `processingAttempts` int(10) unsigned NOT NULL DEFAULT 0,
  `processingMessage` varchar(2000) DEFAULT NULL,
  `processedAt` datetime(3) DEFAULT NULL,
  `isCanonical` tinyint(1) NOT NULL DEFAULT 1,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`registryEventUid`),
  UNIQUE KEY `ukIdentityRegistryBlockchainEvent` (`chainId`,`txHash`,`logIndex`),
  KEY `idxIdentityRegistryEventProcessing` (`chainId`,`processingStatus`,`isCanonical`,`isDeleted`,`blockNumber`),
  KEY `idxIdentityRegistryEventMatch` (`chainId`,`identityRegistryAddress`,`investorWalletAddress`,`investorIdentityAddress`,`blockNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `identityRegistryRegistration` (
  `registryRegistrationUid` char(36) NOT NULL,
  `interestUid` char(36) NOT NULL,
  `tokenUid` char(36) NOT NULL,
  `organizationUid` char(36) NOT NULL,
  `investorUid` char(36) NOT NULL,
  `issuerUserUid` char(36) NOT NULL,
  `chainId` bigint(20) unsigned NOT NULL,
  `identityRegistryAddress` varchar(42) NOT NULL,
  `issuerWalletAddress` varchar(42) NOT NULL,
  `investorWalletAddress` varchar(42) NOT NULL,
  `investorIdentityAddress` varchar(42) NOT NULL,
  `countryCode` smallint(5) unsigned NOT NULL,
  `status` enum('PENDING','CONFIRMED') NOT NULL DEFAULT 'PENDING',
  `txHash` varchar(66) DEFAULT NULL,
  `preparedAtBlock` bigint(20) unsigned DEFAULT NULL,
  `lastScannedBlock` bigint(20) unsigned DEFAULT NULL,
  `blockNumber` bigint(20) unsigned DEFAULT NULL,
  `blockHash` varchar(66) DEFAULT NULL,
  `transactionIndex` int(10) unsigned DEFAULT NULL,
  `logIndex` int(10) unsigned DEFAULT NULL,
  `verifiedAt` datetime(3) DEFAULT NULL,
  `errorCode` varchar(80) DEFAULT NULL,
  `errorMessage` varchar(1000) DEFAULT NULL,
  `syncStatus` enum('IDLE','QUEUED','PROCESSING','FAILED') NOT NULL DEFAULT 'IDLE',
  `syncRequestedAt` datetime(3) DEFAULT NULL,
  `syncStartedAt` datetime(3) DEFAULT NULL,
  `syncCompletedAt` datetime(3) DEFAULT NULL,
  `syncAttempts` int(10) unsigned NOT NULL DEFAULT 0,
  `nextSyncAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`registryRegistrationUid`),
  UNIQUE KEY `ukIdentityRegistryRegistrationInterest` (`interestUid`),
  UNIQUE KEY `ukIdentityRegistryRegistrationTxHash` (`txHash`),
  KEY `idxIdentityRegistryRegistrationRecovery` (`status`,`syncStatus`,`nextSyncAt`,`isDeleted`,`createdAt`),
  KEY `idxIdentityRegistryRegistrationMatch` (`chainId`,`identityRegistryAddress`,`investorWalletAddress`,`investorIdentityAddress`,`status`,`isDeleted`),
  KEY `idxIdentityRegistryRegistrationIssuer` (`organizationUid`,`issuerUserUid`,`status`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `industryMaster` (
  `industryUid` char(36) NOT NULL,
  `industryCode` varchar(50) NOT NULL,
  `industryName` varchar(120) NOT NULL,
  `displayOrder` int(10) unsigned NOT NULL DEFAULT 0,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`industryUid`),
  UNIQUE KEY `ukIndustryMasterCode` (`industryCode`),
  KEY `idxIndustryMasterStatus` (`isActive`,`isDeleted`,`displayOrder`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `investmentSubmissionDocument` (
  `submissionDocumentUid` char(36) NOT NULL,
  `historyUid` char(36) NOT NULL,
  `interestUid` char(36) NOT NULL,
  `tokenUid` char(36) NOT NULL,
  `organizationUid` char(36) NOT NULL,
  `investorUid` char(36) NOT NULL,
  `submissionNumber` int(11) NOT NULL,
  `documentUid` char(36) NOT NULL,
  `documentTypeUid` char(36) DEFAULT NULL,
  `documentTypeName` varchar(150) DEFAULT NULL,
  `documentCategory` varchar(20) DEFAULT NULL,
  `claimTopicCode` varchar(80) DEFAULT NULL,
  `versionNumber` int(11) DEFAULT NULL,
  `originalFileName` varchar(255) DEFAULT NULL,
  `storageKey` varchar(500) DEFAULT NULL,
  `mimeType` varchar(100) DEFAULT NULL,
  `fileSize` bigint(20) unsigned DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`submissionDocumentUid`),
  KEY `idxSubmissionDocInterest` (`interestUid`,`submissionNumber`),
  KEY `idxSubmissionDocHistory` (`historyUid`),
  KEY `idxSubmissionDocDocument` (`interestUid`,`documentUid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `investorClaimBlockchainEvent` (
  `claimEventUid` char(36) NOT NULL,
  `chainId` bigint(20) unsigned NOT NULL,
  `identityAddress` varchar(42) NOT NULL,
  `claimId` varchar(66) NOT NULL,
  `claimTopic` int(11) NOT NULL,
  `scheme` int(11) NOT NULL,
  `issuerIdentityAddress` varchar(42) NOT NULL,
  `data` longtext DEFAULT NULL,
  `signature` longtext DEFAULT NULL,
  `uri` text DEFAULT NULL,
  `eventName` enum('ClaimAdded','ClaimChanged') NOT NULL,
  `txHash` varchar(66) NOT NULL,
  `blockNumber` bigint(20) unsigned NOT NULL,
  `blockHash` varchar(66) DEFAULT NULL,
  `transactionIndex` int(10) unsigned NOT NULL,
  `logIndex` int(10) unsigned NOT NULL,
  `processingStatus` enum('NEW','MATCHED','UNMATCHED','FAILED') NOT NULL DEFAULT 'NEW',
  `matchedSubmissionUid` char(36) DEFAULT NULL,
  `processingAttempts` int(10) unsigned NOT NULL DEFAULT 0,
  `processingMessage` varchar(2000) DEFAULT NULL,
  `processedAt` datetime(3) DEFAULT NULL,
  `isCanonical` tinyint(1) NOT NULL DEFAULT 1,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`claimEventUid`),
  UNIQUE KEY `ukInvestorClaimBlockchainEvent` (`chainId`,`txHash`,`logIndex`),
  KEY `idxInvestorClaimEventProcessing` (`chainId`,`processingStatus`,`isCanonical`,`isDeleted`,`blockNumber`),
  KEY `idxInvestorClaimEventIdentity` (`chainId`,`identityAddress`,`claimTopic`,`issuerIdentityAddress`,`blockNumber`),
  KEY `idxInvestorClaimEventClaimId` (`chainId`,`claimId`,`blockNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `investorClaimSubmission` (
  `submissionUid` char(36) NOT NULL,
  `interestUid` char(36) NOT NULL,
  `claimSignatureUid` char(36) NOT NULL,
  `investorUid` char(36) NOT NULL,
  `tokenUid` char(36) NOT NULL,
  `organizationUid` char(36) NOT NULL,
  `claimTopic` int(11) NOT NULL,
  `data` text DEFAULT NULL,
  `signature` text DEFAULT NULL,
  `investorIdentityAddress` varchar(42) DEFAULT NULL,
  `issuerIdentityAddress` varchar(42) DEFAULT NULL,
  `preparedAtBlock` bigint(20) DEFAULT NULL,
  `lastScannedBlock` bigint(20) DEFAULT NULL,
  `txHash` varchar(66) DEFAULT NULL,
  `blockNumber` bigint(20) DEFAULT NULL,
  `transactionIndex` int(11) DEFAULT NULL,
  `logIndex` int(11) DEFAULT NULL,
  `status` enum('PENDING','CONFIRMED','FAILED') NOT NULL DEFAULT 'PENDING',
  `failureReason` varchar(255) DEFAULT NULL,
  `syncStatus` enum('IDLE','QUEUED','PROCESSING','FAILED') NOT NULL DEFAULT 'IDLE',
  `syncRequestedAt` datetime(3) DEFAULT NULL,
  `syncStartedAt` datetime(3) DEFAULT NULL,
  `syncCompletedAt` datetime(3) DEFAULT NULL,
  `syncAttempts` int(10) unsigned NOT NULL DEFAULT 0,
  `syncFailureReason` varchar(1000) DEFAULT NULL,
  `nextSyncAt` datetime(3) DEFAULT NULL,
  `submittedAt` datetime(3) DEFAULT NULL,
  `confirmedAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`submissionUid`),
  UNIQUE KEY `ukInvestorClaimSubmission` (`interestUid`,`claimSignatureUid`),
  UNIQUE KEY `ukInvestorClaimSubmissionEvent` (`txHash`,`logIndex`),
  KEY `idxInvestorClaimSubmissionInterest` (`interestUid`,`status`,`isDeleted`),
  KEY `idxInvestorClaimSubmissionInvestor` (`investorUid`,`isDeleted`),
  KEY `idxInvestorClaimSubmissionRecovery` (`status`,`txHash`,`syncStatus`,`isDeleted`,`createdAt`),
  KEY `idxInvestorClaimSubmissionChainMatch` (`investorIdentityAddress`,`issuerIdentityAddress`,`claimTopic`,`status`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `investorDocument` (
  `documentUid` char(36) NOT NULL,
  `investorUid` char(36) NOT NULL,
  `documentTypeUid` char(36) NOT NULL,
  `versionNumber` int(11) NOT NULL DEFAULT 1,
  `isCurrent` tinyint(1) NOT NULL DEFAULT 1,
  `uploadedByUserUid` char(36) DEFAULT NULL,
  `documentCategory` enum('kyc','accredited') NOT NULL,
  `claimTopicCode` varchar(80) DEFAULT NULL,
  `originalFileName` varchar(255) NOT NULL,
  `storedFileName` varchar(255) NOT NULL,
  `storageKey` varchar(500) NOT NULL,
  `mimeType` varchar(100) NOT NULL,
  `fileSize` bigint(20) unsigned NOT NULL,
  `checksumSha256` char(64) NOT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`documentUid`),
  UNIQUE KEY `ukInvestorDocumentStorageKey` (`storageKey`),
  KEY `idxInvestorDocumentInvestor` (`investorUid`,`documentCategory`,`isActive`,`isDeleted`),
  KEY `idxInvestorDocumentType` (`documentTypeUid`),
  KEY `idxInvestorDocumentClaimTopic` (`investorUid`,`claimTopicCode`,`isActive`,`isDeleted`),
  KEY `idxInvestorDocumentCurrent` (`investorUid`,`documentTypeUid`,`isCurrent`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `investorDocumentTypeMaster` (
  `documentTypeUid` char(36) NOT NULL,
  `documentTypeCode` varchar(80) NOT NULL,
  `documentTypeName` varchar(150) NOT NULL,
  `documentCategory` enum('kyc','accredited') NOT NULL,
  `claimTopicCode` varchar(80) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `isRequired` tinyint(1) NOT NULL DEFAULT 0,
  `displayOrder` int(10) unsigned NOT NULL DEFAULT 0,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`documentTypeUid`),
  UNIQUE KEY `ukInvestorDocumentTypeCode` (`documentTypeCode`),
  KEY `idxInvestorDocumentTypeCategory` (`documentCategory`,`isActive`,`isDeleted`,`displayOrder`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `investorInvestmentCategory` (
  `investorInvestmentCategoryUid` char(36) NOT NULL,
  `investorUid` char(36) NOT NULL,
  `categoryCode` varchar(40) NOT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`investorInvestmentCategoryUid`),
  UNIQUE KEY `ukInvestorInvestmentCategory` (`investorUid`,`categoryCode`),
  KEY `idxInvestorInvestmentCategory` (`investorUid`,`isActive`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `investorInvitation` (
  `invitationUid` char(36) NOT NULL,
  `organizationUid` char(36) NOT NULL,
  `tokenUid` char(36) NOT NULL,
  `issuerUserUid` char(36) NOT NULL,
  `investorUid` char(36) NOT NULL,
  `investorUserUid` char(36) NOT NULL,
  `status` enum('PENDING','SENT','VIEWED') NOT NULL DEFAULT 'PENDING',
  `emailStatus` enum('PENDING','PROCESSING','SENT','FAILED') NOT NULL DEFAULT 'PENDING',
  `emailAttempts` int(10) unsigned NOT NULL DEFAULT 0,
  `emailMessageId` varchar(255) DEFAULT NULL,
  `emailClaimedAt` datetime(3) DEFAULT NULL,
  `lastEmailError` varchar(2000) DEFAULT NULL,
  `sentAt` datetime(3) DEFAULT NULL,
  `viewedAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`invitationUid`),
  UNIQUE KEY `ukInvestorInvitation` (`organizationUid`,`tokenUid`,`investorUid`),
  KEY `idxInvestorInvitationIssuer` (`issuerUserUid`,`tokenUid`,`status`,`isDeleted`),
  KEY `idxInvestorInvitationInvestor` (`investorUid`,`status`,`sentAt`,`isDeleted`),
  KEY `idxInvestorInvitationEmail` (`emailStatus`,`emailClaimedAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `investorMaster` (
  `investorUid` char(36) NOT NULL,
  `userUid` char(36) NOT NULL,
  `firstName` varchar(50) DEFAULT NULL,
  `lastName` varchar(50) DEFAULT NULL,
  `dateOfBirth` date DEFAULT NULL,
  `gender` enum('male','female','other') DEFAULT NULL,
  `streetAddress` varchar(150) DEFAULT NULL,
  `countryUid` char(36) DEFAULT NULL,
  `stateUid` char(36) DEFAULT NULL,
  `cityUid` char(36) DEFAULT NULL,
  `sourceOfWealth` varchar(120) DEFAULT NULL,
  `estimatedNetWorth` varchar(60) DEFAULT NULL,
  `annualInvestmentCapacity` varchar(60) DEFAULT NULL,
  `yearsOfExperience` tinyint(3) unsigned DEFAULT NULL,
  `previousRwaExperience` enum('yes','no') DEFAULT NULL,
  `rwaExperienceDescription` varchar(600) DEFAULT NULL,
  `accreditationType` enum('individual','institutional','qualified_professional') DEFAULT NULL,
  `walletAddress` varchar(42) DEFAULT NULL,
  `registeredWalletAddress` varchar(42) GENERATED ALWAYS AS (case when `status` = 'submitted' and `walletAddress` is not null and trim(`walletAddress`) <> '' then lcase(trim(`walletAddress`)) else NULL end) STORED,
  `profileReference` varchar(60) DEFAULT NULL,
  `onchainIdReference` varchar(120) DEFAULT NULL,
  `contractAddress` varchar(42) DEFAULT NULL,
  `contractTxnHash` varchar(66) DEFAULT NULL,
  `contractTxnMessage` text DEFAULT NULL,
  `currentStep` enum('identityDetails','identityDocuments','compliance','completed') NOT NULL DEFAULT 'identityDetails',
  `isDraft` tinyint(1) NOT NULL DEFAULT 1,
  `status` enum('draft','submitted') NOT NULL DEFAULT 'draft',
  `submittedAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`investorUid`),
  UNIQUE KEY `ukInvestorMasterUserUid` (`userUid`),
  UNIQUE KEY `ukInvestorMasterProfileReference` (`profileReference`),
  UNIQUE KEY `ukInvestorMasterRegisteredWallet` (`registeredWalletAddress`),
  KEY `idxInvestorMasterStatus` (`status`,`isDraft`,`isActive`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `issuerClaimSignature` (
  `signatureUid` char(36) NOT NULL,
  `verificationUid` char(36) NOT NULL,
  `interestUid` char(36) NOT NULL,
  `claimTopic` int(11) NOT NULL,
  `data` text DEFAULT NULL,
  `signature` text DEFAULT NULL,
  `signedByWallet` varchar(42) DEFAULT NULL,
  `status` enum('PENDING','VERIFICATION_FAILED','NETWORK_ERROR','SIGNED') NOT NULL DEFAULT 'PENDING',
  `verificationError` text DEFAULT NULL,
  `verifiedAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`signatureUid`),
  UNIQUE KEY `ukIssuerClaimSignatureTopic` (`verificationUid`,`claimTopic`),
  KEY `idxIssuerClaimSignatureVerification` (`verificationUid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `issuerClaimVerification` (
  `verificationUid` char(36) NOT NULL,
  `interestUid` char(36) NOT NULL,
  `tokenUid` char(36) NOT NULL,
  `organizationUid` char(36) NOT NULL,
  `investorUid` char(36) NOT NULL,
  `status` enum('PENDING','VERIFICATION_FAILED','NETWORK_ERROR','SIGNED') NOT NULL DEFAULT 'PENDING',
  `requiredClaimCount` int(11) NOT NULL,
  `verifiedClaimCount` int(11) NOT NULL DEFAULT 0,
  `requiredClaimTopics` varchar(255) DEFAULT NULL,
  `attemptNumber` int(11) NOT NULL,
  `completedAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`verificationUid`),
  UNIQUE KEY `ukIssuerClaimVerificationAttempt` (`interestUid`,`attemptNumber`),
  KEY `idxIssuerClaimVerificationInterest` (`interestUid`,`status`,`isDeleted`),
  KEY `idxIssuerClaimVerificationOrg` (`organizationUid`,`status`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `menuMaster` (
  `menuUid` char(36) NOT NULL,
  `parentMenuUid` char(36) DEFAULT NULL,
  `menuName` varchar(100) NOT NULL,
  `menuCode` varchar(80) NOT NULL,
  `routePath` varchar(255) DEFAULT NULL,
  `icon` varchar(100) DEFAULT NULL,
  `displayOrder` int(10) unsigned NOT NULL DEFAULT 0,
  `isVisible` tinyint(1) NOT NULL DEFAULT 1,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`menuUid`),
  UNIQUE KEY `ukMenuMasterMenuCode` (`menuCode`),
  KEY `idxMenuMasterParentMenuUid` (`parentMenuUid`),
  KEY `idxMenuMasterOrder` (`displayOrder`,`isActive`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `organizationBeneficialOwner` (
  `beneficialOwnerUid` char(36) NOT NULL,
  `organizationUid` char(36) NOT NULL,
  `fullName` varchar(120) DEFAULT NULL,
  `dateOfBirth` date DEFAULT NULL,
  `nationalityCountryUid` char(36) DEFAULT NULL,
  `ownershipPercentage` decimal(5,2) DEFAULT NULL,
  `isPrimary` tinyint(1) NOT NULL DEFAULT 0,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`beneficialOwnerUid`),
  KEY `idxOrganizationBeneficialOwnerOrganization` (`organizationUid`,`isActive`,`isDeleted`),
  KEY `idxOrganizationBeneficialOwnerNationality` (`nationalityCountryUid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `organizationDocument` (
  `documentUid` char(36) NOT NULL,
  `organizationUid` char(36) NOT NULL,
  `documentTypeUid` char(36) NOT NULL,
  `originalFileName` varchar(255) NOT NULL,
  `storedFileName` varchar(255) NOT NULL,
  `storageKey` varchar(500) NOT NULL,
  `mimeType` varchar(100) NOT NULL,
  `fileSize` bigint(20) unsigned NOT NULL,
  `checksumSha256` char(64) NOT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`documentUid`),
  UNIQUE KEY `ukOrganizationDocumentStorageKey` (`storageKey`),
  KEY `idxOrganizationDocumentOrganization` (`organizationUid`,`documentTypeUid`,`isActive`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `organizationMaster` (
  `organizationUid` char(36) NOT NULL,
  `userUid` char(36) NOT NULL,
  `legalCompanyName` varchar(200) DEFAULT NULL,
  `entityTypeUid` char(36) DEFAULT NULL,
  `registrationNumber` varchar(100) DEFAULT NULL,
  `streetAddress` varchar(255) DEFAULT NULL,
  `countryUid` char(36) DEFAULT NULL,
  `stateUid` char(36) DEFAULT NULL,
  `cityUid` char(36) DEFAULT NULL,
  `postalCode` varchar(20) DEFAULT NULL,
  `countryOfIncorporationUid` char(36) DEFAULT NULL,
  `dateOfIncorporation` date DEFAULT NULL,
  `taxIdentificationNumber` varchar(100) DEFAULT NULL,
  `industryUid` char(36) DEFAULT NULL,
  `businessActivity` text DEFAULT NULL,
  `website` varchar(500) DEFAULT NULL,
  `walletAddress` varchar(42) DEFAULT NULL,
  `registeredWalletAddress` varchar(42) GENERATED ALWAYS AS (case when `walletAddress` is not null and trim(`walletAddress`) <> '' and `isDeleted` = 0 then lcase(trim(`walletAddress`)) else NULL end) STORED,
  `contractAddress` varchar(42) DEFAULT NULL,
  `contractTxnHash` varchar(66) DEFAULT NULL,
  `contractTxnMessage` text DEFAULT NULL,
  `currentStep` enum('companyInformation','jurisdiction','beneficialOwners','documents','completed') NOT NULL DEFAULT 'companyInformation',
  `isDraft` tinyint(1) NOT NULL DEFAULT 1,
  `status` enum('draft','submitted','resubmitted','underReview','approved','rejected') NOT NULL DEFAULT 'draft',
  `isUserNotified` tinyint(1) NOT NULL DEFAULT 0,
  `submittedAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  `rejectionReason` text DEFAULT NULL,
  `rejectionCount` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `canResubmit` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`organizationUid`),
  UNIQUE KEY `ukOrganizationMasterUserUid` (`userUid`),
  UNIQUE KEY `ukOrganizationRegistration` (`countryOfIncorporationUid`,`registrationNumber`),
  UNIQUE KEY `ukOrganizationMasterRegisteredWallet` (`registeredWalletAddress`),
  KEY `idxOrganizationMasterStatus` (`status`,`isDraft`,`isActive`,`isDeleted`),
  KEY `idxOrganizationMasterLocation` (`countryUid`,`stateUid`,`cityUid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `permissionMaster` (
  `permissionUid` char(36) NOT NULL,
  `roleUid` char(36) NOT NULL,
  `menuUid` char(36) DEFAULT NULL,
  `permissionName` varchar(120) NOT NULL,
  `permissionCode` varchar(120) NOT NULL,
  `httpMethod` enum('GET','POST','PUT','PATCH','DELETE') NOT NULL,
  `apiPath` varchar(255) NOT NULL,
  `isAllowed` tinyint(1) NOT NULL DEFAULT 1,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`permissionUid`),
  UNIQUE KEY `ukPermissionMasterApi` (`roleUid`,`httpMethod`,`apiPath`),
  UNIQUE KEY `ukPermissionMasterCode` (`roleUid`,`permissionCode`),
  KEY `idxPermissionMasterMenuUid` (`menuUid`),
  KEY `idxPermissionMasterLookup` (`roleUid`,`isAllowed`,`isActive`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `stateMaster` (
  `stateUid` char(36) NOT NULL,
  `countryUid` char(36) NOT NULL,
  `stateCode` varchar(20) NOT NULL,
  `stateName` varchar(120) NOT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`stateUid`),
  UNIQUE KEY `ukStateMasterCode` (`countryUid`,`stateCode`),
  KEY `idxStateMasterCountryName` (`countryUid`,`stateName`,`isActive`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tokenClaimTopic` (
  `tokenClaimTopicUid` char(36) NOT NULL,
  `tokenUid` char(36) NOT NULL,
  `claimTopicUid` char(36) NOT NULL,
  `claimTopicValue` int(10) unsigned NOT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`tokenClaimTopicUid`),
  UNIQUE KEY `ukTokenClaimTopicSelection` (`tokenUid`,`claimTopicUid`),
  KEY `idxTokenClaimTopicValue` (`tokenUid`,`claimTopicValue`,`isActive`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tokenCountryRestriction` (
  `tokenCountryRestrictionUid` char(36) NOT NULL,
  `tokenUid` char(36) NOT NULL,
  `countryUid` char(36) NOT NULL,
  `iso3166NumericCode` char(3) NOT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`tokenCountryRestrictionUid`),
  UNIQUE KEY `ukTokenCountryRestrictionSelection` (`tokenUid`,`countryUid`),
  KEY `idxTokenCountryRestrictionCode` (`tokenUid`,`iso3166NumericCode`,`isActive`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tokenDeploymentAttempt` (
  `deploymentAttemptUid` char(36) NOT NULL,
  `tokenUid` char(36) NOT NULL,
  `organizationUid` char(36) NOT NULL,
  `userUid` char(36) NOT NULL,
  `walletAddress` varchar(42) NOT NULL,
  `chainId` int(10) unsigned NOT NULL,
  `networkName` varchar(50) DEFAULT NULL,
  `status` enum('pending','submitted','confirming','confirmed','failed','wallet_rejected','cancelled','expired') NOT NULL DEFAULT 'pending',
  `idempotencyKey` varchar(100) NOT NULL,
  `transactionHash` varchar(66) DEFAULT NULL,
  `contractAddress` varchar(42) DEFAULT NULL,
  `blockNumber` bigint(20) unsigned DEFAULT NULL,
  `errorCode` varchar(80) DEFAULT NULL,
  `errorMessage` text DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `expiresAt` datetime(3) DEFAULT NULL,
  `submittedAt` datetime(3) DEFAULT NULL,
  `confirmedAt` datetime(3) DEFAULT NULL,
  `failedAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`deploymentAttemptUid`),
  UNIQUE KEY `ukTokenDeploymentAttemptIdempotency` (`tokenUid`,`idempotencyKey`),
  UNIQUE KEY `ukTokenDeploymentAttemptTxHash` (`transactionHash`),
  KEY `idxTokenDeploymentAttemptToken` (`tokenUid`,`status`,`isDeleted`),
  KEY `idxTokenDeploymentAttemptOrganization` (`organizationUid`),
  KEY `idxTokenDeploymentAttemptUser` (`userUid`),
  KEY `idxTokenDeploymentAttemptStatus` (`status`,`expiresAt`),
  KEY `idxTokenDeploymentAttemptExpiry` (`expiresAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tokenInvestmentInterest` (
  `interestUid` char(36) NOT NULL,
  `tokenUid` char(36) NOT NULL,
  `organizationUid` char(36) NOT NULL,
  `investorUid` char(36) NOT NULL,
  `investorUserUid` char(36) NOT NULL,
  `walletAddress` varchar(42) DEFAULT NULL,
  `status` enum('pending','submitIntrest','verifiedByIssuer','claimSubmitted','registered','approved','rejected','cancelled') NOT NULL DEFAULT 'pending',
  `note` varchar(500) DEFAULT NULL,
  `rejectReasonType` varchar(40) DEFAULT NULL,
  `rejectReason` varchar(1000) DEFAULT NULL,
  `rejectedClaim` varchar(500) DEFAULT NULL,
  `rejectedCount` int(11) NOT NULL DEFAULT 3,
  `canResubmitClaim` int(11) NOT NULL DEFAULT 0,
  `submittedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `decisionAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`interestUid`),
  UNIQUE KEY `ukTokenInvestmentInterest` (`tokenUid`,`investorUid`),
  KEY `idxTokenInvestmentInterestOrg` (`organizationUid`,`status`,`isDeleted`),
  KEY `idxTokenInvestmentInterestToken` (`tokenUid`,`status`,`isDeleted`),
  KEY `idxTokenInvestmentInterestInvestor` (`investorUid`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tokenInvestmentInterestHistory` (
  `historyUid` char(36) NOT NULL,
  `interestUid` char(36) NOT NULL,
  `tokenUid` char(36) NOT NULL,
  `organizationUid` char(36) NOT NULL,
  `investorUid` char(36) NOT NULL,
  `eventType` enum('submitted','rejected','resubmitted','approved','verifiedByIssuer','claimSubmitted','registered') NOT NULL,
  `rejectReasonType` varchar(40) DEFAULT NULL,
  `rejectReason` varchar(1000) DEFAULT NULL,
  `rejectedClaim` varchar(500) DEFAULT NULL,
  `resubmitAttempt` int(11) DEFAULT NULL,
  `actorRole` enum('investor','issuer','system') NOT NULL DEFAULT 'system',
  `actorUserUid` char(36) DEFAULT NULL,
  `note` varchar(1000) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`historyUid`),
  KEY `idxInterestHistoryInterest` (`interestUid`,`createdAt`),
  KEY `idxInterestHistoryOrg` (`organizationUid`,`eventType`,`isDeleted`),
  KEY `idxInterestHistoryInvestor` (`investorUid`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tokenMaster` (
  `tokenUid` char(36) NOT NULL,
  `organizationUid` char(36) NOT NULL,
  `userUid` char(36) NOT NULL,
  `tokenName` varchar(50) DEFAULT NULL,
  `tokenSymbol` varchar(10) DEFAULT NULL,
  `decimals` tinyint(3) unsigned DEFAULT NULL,
  `initialTokenPrice` decimal(36,18) DEFAULT NULL,
  `currentTokenPrice` decimal(36,18) DEFAULT NULL,
  `treasuryWalletAddress` varchar(42) DEFAULT NULL,
  `tokenDescription` varchar(2000) DEFAULT NULL,
  `imageOriginalFileName` varchar(255) DEFAULT NULL,
  `imageStorageKey` varchar(255) DEFAULT NULL,
  `imageMimeType` varchar(50) DEFAULT NULL,
  `imageFileSize` int(10) unsigned DEFAULT NULL,
  `imageWidth` smallint(5) unsigned DEFAULT NULL,
  `imageHeight` smallint(5) unsigned DEFAULT NULL,
  `imageChecksumSha256` char(64) DEFAULT NULL,
  `imageVirusScanStatus` enum('notConfigured','clean') NOT NULL DEFAULT 'notConfigured',
  `trustedClaimIssuerWalletAddress` varchar(42) DEFAULT NULL,
  `maxInvestors` int(10) unsigned DEFAULT NULL,
  `maxBalancePerInvestor` decimal(36,18) DEFAULT NULL,
  `countryRestrictionMode` enum('allowlist','blocklist') DEFAULT NULL,
  `tokenAgentWalletAddress` varchar(42) DEFAULT NULL,
  `identityManagerWalletAddress` varchar(42) DEFAULT NULL,
  `platformAgentWallet` varchar(42) DEFAULT NULL,
  `tokenAddress` varchar(42) DEFAULT NULL,
  `identityRegistryAddress` varchar(42) DEFAULT NULL,
  `identityRegistryStorageAddress` varchar(42) DEFAULT NULL,
  `trustedIssuersRegistryAddress` varchar(42) DEFAULT NULL,
  `claimTopicsRegistryAddress` varchar(42) DEFAULT NULL,
  `modularComplianceAddress` varchar(42) DEFAULT NULL,
  `deployTxHash` varchar(66) DEFAULT NULL,
  `deploymentSalt` varchar(66) DEFAULT NULL,
  `deployedAtBlock` bigint(20) unsigned DEFAULT NULL,
  `currentStep` enum('tokenInformation','claims','compliance','governance','review','deployed') NOT NULL DEFAULT 'tokenInformation',
  `isDraft` tinyint(1) NOT NULL DEFAULT 1,
  `status` enum('draft','readyToDeploy','deploymentPending','deployed','deploymentFailed') NOT NULL DEFAULT 'draft',
  `contractAddress` varchar(42) DEFAULT NULL,
  `contractTxnHash` varchar(66) DEFAULT NULL,
  `contractTxnMessage` text DEFAULT NULL,
  `deployedAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`tokenUid`),
  UNIQUE KEY `ukTokenMasterOrganizationUid` (`organizationUid`),
  UNIQUE KEY `ukTokenMasterSymbol` (`tokenSymbol`),
  UNIQUE KEY `ukTokenMasterTokenAddress` (`tokenAddress`),
  UNIQUE KEY `ukTokenMasterDeployTxHash` (`deployTxHash`),
  KEY `idxTokenMasterUserUid` (`userUid`),
  KEY `idxTokenMasterStatus` (`status`,`isActive`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tokenPurchase` (
  `purchaseUid` char(36) NOT NULL,
  `interestUid` char(36) NOT NULL,
  `tokenUid` char(36) NOT NULL,
  `organizationUid` char(36) NOT NULL,
  `investorUid` char(36) NOT NULL,
  `investorUserUid` char(36) NOT NULL,
  `idempotencyKey` varchar(100) NOT NULL,
  `chainId` bigint(20) unsigned NOT NULL,
  `usdtContractAddress` varchar(42) NOT NULL,
  `tokenAddress` varchar(42) NOT NULL,
  `investorWalletAddress` varchar(42) NOT NULL,
  `treasuryWalletAddress` varchar(42) NOT NULL,
  `platformWalletAddress` varchar(42) NOT NULL,
  `usdtDecimals` tinyint(3) unsigned NOT NULL,
  `tokenDecimals` tinyint(3) unsigned NOT NULL,
  `tokenPrice` decimal(65,18) NOT NULL,
  `tokenAmount` decimal(65,18) NOT NULL,
  `tokenAmountRaw` varchar(78) NOT NULL,
  `usdtAmount` decimal(65,18) NOT NULL,
  `usdtAmountRaw` varchar(78) NOT NULL,
  `balanceBeforeRaw` varchar(78) NOT NULL,
  `status` enum('PENDING_PAYMENT','PAYMENT_CONFIRMED','MINT_SUBMITTED','COMPLETED','EXPIRED') NOT NULL DEFAULT 'PENDING_PAYMENT',
  `activeInterestUid` char(36) GENERATED ALWAYS AS (case when `status` in ('PENDING_PAYMENT','PAYMENT_CONFIRMED','MINT_SUBMITTED') then `interestUid` else NULL end) STORED,
  `activeInvestorUid` char(36) GENERATED ALWAYS AS (case when `status` in ('PENDING_PAYMENT','PAYMENT_CONFIRMED','MINT_SUBMITTED') then `investorUid` else NULL end) STORED,
  `expiresAt` datetime(3) NOT NULL,
  `expiredAt` datetime(3) DEFAULT NULL,
  `expirationReason` varchar(100) DEFAULT NULL,
  `paymentTxHash` varchar(66) DEFAULT NULL,
  `paymentTxReceivedAt` datetime(3) DEFAULT NULL,
  `paymentBlockNumber` bigint(20) unsigned DEFAULT NULL,
  `paymentBlockHash` varchar(66) DEFAULT NULL,
  `paymentTransactionIndex` int(10) unsigned DEFAULT NULL,
  `paymentLogIndex` int(10) unsigned DEFAULT NULL,
  `paymentGasUsed` varchar(78) DEFAULT NULL,
  `paymentEffectiveGasPrice` varchar(78) DEFAULT NULL,
  `paymentVerifiedAt` datetime(3) DEFAULT NULL,
  `mintStatus` enum('NOT_STARTED','QUEUED','PROCESSING','SUBMITTED','CONFIRMED','FAILED') NOT NULL DEFAULT 'NOT_STARTED',
  `mintPreparedAtBlock` bigint(20) unsigned DEFAULT NULL,
  `mintTxHash` varchar(66) DEFAULT NULL,
  `mintSubmittedAt` datetime(3) DEFAULT NULL,
  `mintBlockNumber` bigint(20) unsigned DEFAULT NULL,
  `mintBlockHash` varchar(66) DEFAULT NULL,
  `mintTransactionIndex` int(10) unsigned DEFAULT NULL,
  `mintLogIndex` int(10) unsigned DEFAULT NULL,
  `mintGasUsed` varchar(78) DEFAULT NULL,
  `mintEffectiveGasPrice` varchar(78) DEFAULT NULL,
  `mintConfirmedAt` datetime(3) DEFAULT NULL,
  `preparedAtBlock` bigint(20) unsigned NOT NULL,
  `lastPaymentScannedBlock` bigint(20) unsigned DEFAULT NULL,
  `lastMintScannedBlock` bigint(20) unsigned DEFAULT NULL,
  `errorStage` enum('PAYMENT','MINT') DEFAULT NULL,
  `errorCode` varchar(100) DEFAULT NULL,
  `errorMessage` varchar(2000) DEFAULT NULL,
  `syncStatus` enum('IDLE','QUEUED','PROCESSING','FAILED') NOT NULL DEFAULT 'IDLE',
  `syncRequestedAt` datetime(3) DEFAULT NULL,
  `syncStartedAt` datetime(3) DEFAULT NULL,
  `syncCompletedAt` datetime(3) DEFAULT NULL,
  `syncAttempts` int(10) unsigned NOT NULL DEFAULT 0,
  `nextSyncAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`purchaseUid`),
  UNIQUE KEY `ukTokenPurchaseIdempotency` (`investorUserUid`,`idempotencyKey`),
  UNIQUE KEY `ukTokenPurchaseActiveInterest` (`activeInterestUid`),
  UNIQUE KEY `ukTokenPurchaseActiveInvestor` (`activeInvestorUid`),
  UNIQUE KEY `ukTokenPurchasePaymentTxHash` (`paymentTxHash`),
  UNIQUE KEY `ukTokenPurchaseMintTxHash` (`mintTxHash`),
  KEY `idxTokenPurchaseRecovery` (`status`,`syncStatus`,`nextSyncAt`,`isDeleted`,`createdAt`),
  KEY `idxTokenPurchaseInvestor` (`investorUserUid`,`createdAt`),
  KEY `idxTokenPurchaseMatch` (`chainId`,`usdtContractAddress`,`investorWalletAddress`,`treasuryWalletAddress`,`status`),
  KEY `idxTokenPurchaseExpiration` (`status`,`paymentTxHash`,`expiresAt`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tokenPurchasePaymentEvent` (
  `paymentEventUid` char(36) NOT NULL,
  `chainId` bigint(20) unsigned NOT NULL,
  `usdtContractAddress` varchar(42) NOT NULL,
  `fromWalletAddress` varchar(42) NOT NULL,
  `toWalletAddress` varchar(42) NOT NULL,
  `amountRaw` varchar(78) NOT NULL,
  `txHash` varchar(66) NOT NULL,
  `blockNumber` bigint(20) unsigned NOT NULL,
  `blockHash` varchar(66) DEFAULT NULL,
  `transactionIndex` int(10) unsigned NOT NULL,
  `logIndex` int(10) unsigned NOT NULL,
  `processingStatus` enum('NEW','MATCHED','UNMATCHED','FAILED') NOT NULL DEFAULT 'NEW',
  `matchedPurchaseUid` char(36) DEFAULT NULL,
  `processingAttempts` int(10) unsigned NOT NULL DEFAULT 0,
  `processingMessage` varchar(2000) DEFAULT NULL,
  `processedAt` datetime(3) DEFAULT NULL,
  `isCanonical` tinyint(1) NOT NULL DEFAULT 1,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`paymentEventUid`),
  UNIQUE KEY `ukTokenPurchasePaymentEvent` (`chainId`,`txHash`,`logIndex`),
  KEY `idxTokenPurchasePaymentEventProcess` (`chainId`,`processingStatus`,`isCanonical`,`blockNumber`),
  KEY `idxTokenPurchasePaymentEventMatch` (`fromWalletAddress`,`toWalletAddress`,`amountRaw`,`blockNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tokenPurchaseTransaction` (
  `purchaseTransactionUid` char(36) NOT NULL,
  `purchaseUid` char(36) NOT NULL,
  `stage` enum('PAYMENT','MINT') NOT NULL,
  `txHash` varchar(66) NOT NULL,
  `status` enum('RECEIVED','SUBMITTED','PENDING','CONFIRMED','FAILED') NOT NULL,
  `blockNumber` bigint(20) unsigned DEFAULT NULL,
  `blockHash` varchar(66) DEFAULT NULL,
  `transactionIndex` int(10) unsigned DEFAULT NULL,
  `logIndex` int(10) unsigned DEFAULT NULL,
  `gasUsed` varchar(78) DEFAULT NULL,
  `effectiveGasPrice` varchar(78) DEFAULT NULL,
  `errorCode` varchar(100) DEFAULT NULL,
  `errorMessage` varchar(2000) DEFAULT NULL,
  `confirmedAt` datetime(3) DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`purchaseTransactionUid`),
  UNIQUE KEY `ukTokenPurchaseTransactionHash` (`txHash`),
  KEY `idxTokenPurchaseTransactionPurchase` (`purchaseUid`,`stage`,`createdAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tokenRedemption` (
  `redemptionUid` char(36) NOT NULL,
  `interestUid` char(36) NOT NULL,
  `tokenUid` char(36) NOT NULL,
  `organizationUid` char(36) NOT NULL,
  `investorUid` char(36) NOT NULL,
  `investorUserUid` char(36) NOT NULL,
  `issuerUserUid` char(36) NOT NULL,
  `idempotencyKey` varchar(100) NOT NULL,
  `chainId` bigint(20) unsigned NOT NULL,
  `usdtContractAddress` varchar(42) NOT NULL,
  `tokenAddress` varchar(42) NOT NULL,
  `investorWalletAddress` varchar(42) NOT NULL,
  `issuerPaymentWalletAddress` varchar(42) NOT NULL,
  `platformWalletAddress` varchar(42) NOT NULL,
  `usdtDecimals` tinyint(3) unsigned NOT NULL,
  `tokenDecimals` tinyint(3) unsigned NOT NULL,
  `tokenPrice` decimal(65,18) NOT NULL,
  `tokenAmount` decimal(65,18) NOT NULL,
  `tokenAmountRaw` varchar(78) NOT NULL,
  `usdtAmount` decimal(65,18) NOT NULL,
  `usdtAmountRaw` varchar(78) NOT NULL,
  `balanceBeforeRaw` varchar(78) NOT NULL,
  `frozenBeforeRaw` varchar(78) NOT NULL,
  `totalSupplyBeforeRaw` varchar(78) NOT NULL,
  `preparedAtBlock` bigint(20) unsigned NOT NULL,
  `status` enum('PENDING_INVESTOR_AUTHORIZATION','PENDING_ISSUER_APPROVAL','ISSUER_APPROVED','TOKEN_LOCK_SUBMITTED','TOKENS_LOCKED','PAYMENT_SUBMITTED','PAYMENT_CONFIRMED','BURN_SUBMITTED','BURN_CONFIRMED','UNLOCK_SUBMITTED','CANCELLATION_PENDING','COMPLETED','ISSUER_REJECTED','CANCELLED','EXPIRED','MANUAL_REVIEW') NOT NULL DEFAULT 'PENDING_INVESTOR_AUTHORIZATION',
  `activeInterestUid` char(36) GENERATED ALWAYS AS (case when `status` not in ('COMPLETED','ISSUER_REJECTED','CANCELLED','EXPIRED') then `interestUid` else NULL end) STORED,
  `authorizationNonce` char(36) NOT NULL,
  `authorizationDeadline` datetime(3) NOT NULL,
  `authorizationSignature` varchar(132) DEFAULT NULL,
  `authorizedAt` datetime(3) DEFAULT NULL,
  `issuerDecisionAt` datetime(3) DEFAULT NULL,
  `issuerDecisionNote` varchar(1000) DEFAULT NULL,
  `rejectionReason` varchar(1000) DEFAULT NULL,
  `expiresAt` datetime(3) NOT NULL,
  `expiredAt` datetime(3) DEFAULT NULL,
  `lockStatus` enum('NOT_STARTED','QUEUED','PROCESSING','SUBMITTED','CONFIRMED','FAILED','NOT_REQUIRED') NOT NULL DEFAULT 'NOT_STARTED',
  `lockPreparedAtBlock` bigint(20) unsigned DEFAULT NULL,
  `lockTxHash` varchar(66) DEFAULT NULL,
  `lockSubmittedAt` datetime(3) DEFAULT NULL,
  `lockBlockNumber` bigint(20) unsigned DEFAULT NULL,
  `lockBlockHash` varchar(66) DEFAULT NULL,
  `lockTransactionIndex` int(10) unsigned DEFAULT NULL,
  `lockLogIndex` int(10) unsigned DEFAULT NULL,
  `lockGasUsed` varchar(78) DEFAULT NULL,
  `lockEffectiveGasPrice` varchar(78) DEFAULT NULL,
  `lockConfirmedAt` datetime(3) DEFAULT NULL,
  `paymentStatus` enum('NOT_STARTED','AWAITING_ISSUER','SUBMITTED','CONFIRMED','FAILED','NOT_REQUIRED') NOT NULL DEFAULT 'NOT_STARTED',
  `paymentRequestedAtBlock` bigint(20) unsigned DEFAULT NULL,
  `paymentTxHash` varchar(66) DEFAULT NULL,
  `paymentTxReceivedAt` datetime(3) DEFAULT NULL,
  `paymentBlockNumber` bigint(20) unsigned DEFAULT NULL,
  `paymentBlockHash` varchar(66) DEFAULT NULL,
  `paymentTransactionIndex` int(10) unsigned DEFAULT NULL,
  `paymentLogIndex` int(10) unsigned DEFAULT NULL,
  `paymentGasUsed` varchar(78) DEFAULT NULL,
  `paymentEffectiveGasPrice` varchar(78) DEFAULT NULL,
  `paymentVerifiedAt` datetime(3) DEFAULT NULL,
  `burnStatus` enum('NOT_STARTED','QUEUED','PROCESSING','SUBMITTED','CONFIRMED','FAILED','NOT_REQUIRED') NOT NULL DEFAULT 'NOT_STARTED',
  `burnPreparedAtBlock` bigint(20) unsigned DEFAULT NULL,
  `burnTxHash` varchar(66) DEFAULT NULL,
  `burnSubmittedAt` datetime(3) DEFAULT NULL,
  `burnBlockNumber` bigint(20) unsigned DEFAULT NULL,
  `burnBlockHash` varchar(66) DEFAULT NULL,
  `burnTransactionIndex` int(10) unsigned DEFAULT NULL,
  `burnLogIndex` int(10) unsigned DEFAULT NULL,
  `burnGasUsed` varchar(78) DEFAULT NULL,
  `burnEffectiveGasPrice` varchar(78) DEFAULT NULL,
  `burnConfirmedAt` datetime(3) DEFAULT NULL,
  `unlockStatus` enum('NOT_STARTED','QUEUED','PROCESSING','SUBMITTED','CONFIRMED','FAILED','NOT_REQUIRED') NOT NULL DEFAULT 'NOT_STARTED',
  `unlockAmountRaw` varchar(78) DEFAULT NULL,
  `unlockPreparedAtBlock` bigint(20) unsigned DEFAULT NULL,
  `unlockTxHash` varchar(66) DEFAULT NULL,
  `unlockSubmittedAt` datetime(3) DEFAULT NULL,
  `unlockBlockNumber` bigint(20) unsigned DEFAULT NULL,
  `unlockBlockHash` varchar(66) DEFAULT NULL,
  `unlockTransactionIndex` int(10) unsigned DEFAULT NULL,
  `unlockLogIndex` int(10) unsigned DEFAULT NULL,
  `unlockGasUsed` varchar(78) DEFAULT NULL,
  `unlockEffectiveGasPrice` varchar(78) DEFAULT NULL,
  `unlockConfirmedAt` datetime(3) DEFAULT NULL,
  `errorStage` enum('AUTHORIZATION','LOCK','PAYMENT','BURN','UNLOCK','SYSTEM') DEFAULT NULL,
  `errorCode` varchar(100) DEFAULT NULL,
  `errorMessage` varchar(2000) DEFAULT NULL,
  `syncStatus` enum('IDLE','QUEUED','PROCESSING','FAILED') NOT NULL DEFAULT 'IDLE',
  `syncRequestedAt` datetime(3) DEFAULT NULL,
  `syncStartedAt` datetime(3) DEFAULT NULL,
  `syncCompletedAt` datetime(3) DEFAULT NULL,
  `syncAttempts` int(10) unsigned NOT NULL DEFAULT 0,
  `nextSyncAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`redemptionUid`),
  UNIQUE KEY `ukTokenRedemptionIdempotency` (`investorUserUid`,`idempotencyKey`),
  UNIQUE KEY `ukTokenRedemptionActiveInterest` (`activeInterestUid`),
  UNIQUE KEY `ukTokenRedemptionLockTxHash` (`lockTxHash`),
  UNIQUE KEY `ukTokenRedemptionPaymentTxHash` (`paymentTxHash`),
  UNIQUE KEY `ukTokenRedemptionBurnTxHash` (`burnTxHash`),
  UNIQUE KEY `ukTokenRedemptionUnlockTxHash` (`unlockTxHash`),
  KEY `idxTokenRedemptionInvestor` (`investorUserUid`,`tokenUid`,`createdAt`),
  KEY `idxTokenRedemptionIssuer` (`issuerUserUid`,`status`,`createdAt`),
  KEY `idxTokenRedemptionRecovery` (`status`,`syncStatus`,`nextSyncAt`,`isDeleted`,`createdAt`),
  KEY `idxTokenRedemptionPaymentMatch` (`chainId`,`usdtContractAddress`,`issuerPaymentWalletAddress`,`investorWalletAddress`,`paymentStatus`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tokenRedemptionHistory` (
  `redemptionHistoryUid` char(36) NOT NULL,
  `redemptionUid` char(36) NOT NULL,
  `eventType` varchar(80) NOT NULL,
  `fromStatus` varchar(50) DEFAULT NULL,
  `toStatus` varchar(50) NOT NULL,
  `actorRole` varchar(30) NOT NULL,
  `actorUserUid` char(36) DEFAULT NULL,
  `message` varchar(1000) DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  PRIMARY KEY (`redemptionHistoryUid`),
  KEY `idxTokenRedemptionHistory` (`redemptionUid`,`createdAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tokenRedemptionPaymentEvent` (
  `redemptionPaymentEventUid` char(36) NOT NULL,
  `chainId` bigint(20) unsigned NOT NULL,
  `usdtContractAddress` varchar(42) NOT NULL,
  `fromWalletAddress` varchar(42) NOT NULL,
  `toWalletAddress` varchar(42) NOT NULL,
  `amountRaw` varchar(78) NOT NULL,
  `txHash` varchar(66) NOT NULL,
  `blockNumber` bigint(20) unsigned NOT NULL,
  `blockHash` varchar(66) DEFAULT NULL,
  `transactionIndex` int(10) unsigned NOT NULL,
  `logIndex` int(10) unsigned NOT NULL,
  `processingStatus` enum('NEW','MATCHED','UNMATCHED','FAILED') NOT NULL DEFAULT 'NEW',
  `matchedRedemptionUid` char(36) DEFAULT NULL,
  `processingAttempts` int(10) unsigned NOT NULL DEFAULT 0,
  `processingMessage` varchar(2000) DEFAULT NULL,
  `processedAt` datetime(3) DEFAULT NULL,
  `isCanonical` tinyint(1) NOT NULL DEFAULT 1,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`redemptionPaymentEventUid`),
  UNIQUE KEY `ukTokenRedemptionPaymentEvent` (`chainId`,`txHash`,`logIndex`),
  KEY `idxTokenRedemptionPaymentEventProcess` (`chainId`,`processingStatus`,`isCanonical`,`blockNumber`),
  KEY `idxTokenRedemptionPaymentEventMatch` (`fromWalletAddress`,`toWalletAddress`,`amountRaw`,`blockNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tokenRedemptionTransaction` (
  `redemptionTransactionUid` char(36) NOT NULL,
  `redemptionUid` char(36) NOT NULL,
  `stage` enum('LOCK','PAYMENT','BURN','UNLOCK') NOT NULL,
  `txHash` varchar(66) NOT NULL,
  `status` enum('RECEIVED','SUBMITTED','PENDING','CONFIRMED','FAILED') NOT NULL,
  `blockNumber` bigint(20) unsigned DEFAULT NULL,
  `blockHash` varchar(66) DEFAULT NULL,
  `transactionIndex` int(10) unsigned DEFAULT NULL,
  `logIndex` int(10) unsigned DEFAULT NULL,
  `gasUsed` varchar(78) DEFAULT NULL,
  `effectiveGasPrice` varchar(78) DEFAULT NULL,
  `errorCode` varchar(100) DEFAULT NULL,
  `errorMessage` varchar(2000) DEFAULT NULL,
  `confirmedAt` datetime(3) DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`redemptionTransactionUid`),
  UNIQUE KEY `ukTokenRedemptionTransactionHash` (`txHash`),
  KEY `idxTokenRedemptionTransaction` (`redemptionUid`,`stage`,`createdAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tokenTransfer` (
  `transferUid` char(36) NOT NULL,
  `tokenUid` char(36) NOT NULL,
  `organizationUid` char(36) NOT NULL,
  `senderInterestUid` char(36) NOT NULL,
  `recipientInterestUid` char(36) NOT NULL,
  `senderInvestorUid` char(36) NOT NULL,
  `recipientInvestorUid` char(36) NOT NULL,
  `senderUserUid` char(36) NOT NULL,
  `recipientUserUid` char(36) NOT NULL,
  `idempotencyKey` varchar(100) NOT NULL,
  `chainId` bigint(20) unsigned NOT NULL,
  `tokenAddress` varchar(42) NOT NULL,
  `identityRegistryAddress` varchar(42) NOT NULL,
  `senderWalletAddress` varchar(42) NOT NULL,
  `recipientWalletAddress` varchar(42) NOT NULL,
  `senderIdentityAddress` varchar(42) NOT NULL,
  `recipientIdentityAddress` varchar(42) NOT NULL,
  `tokenDecimals` tinyint(3) unsigned NOT NULL,
  `tokenPrice` decimal(65,18) NOT NULL,
  `tokenAmount` decimal(65,18) NOT NULL,
  `tokenAmountRaw` varchar(78) NOT NULL,
  `senderBalanceBeforeRaw` varchar(78) NOT NULL,
  `recipientBalanceBeforeRaw` varchar(78) NOT NULL,
  `senderFrozenBeforeRaw` varchar(78) NOT NULL,
  `preparedAtBlock` bigint(20) unsigned NOT NULL,
  `status` enum('PENDING_TRANSFER','COMPLETED','EXPIRED','MANUAL_REVIEW') NOT NULL DEFAULT 'PENDING_TRANSFER',
  `activeSenderTokenKey` varchar(100) GENERATED ALWAYS AS (case when `status` = 'PENDING_TRANSFER' then concat(lcase(`senderWalletAddress`),':',lcase(`tokenAddress`)) else NULL end) STORED,
  `expiresAt` datetime(3) NOT NULL,
  `expiredAt` datetime(3) DEFAULT NULL,
  `expirationReason` varchar(100) DEFAULT NULL,
  `txHash` varchar(66) DEFAULT NULL,
  `txHashReceivedAt` datetime(3) DEFAULT NULL,
  `blockNumber` bigint(20) unsigned DEFAULT NULL,
  `blockHash` varchar(66) DEFAULT NULL,
  `transactionIndex` int(10) unsigned DEFAULT NULL,
  `logIndex` int(10) unsigned DEFAULT NULL,
  `gasUsed` varchar(78) DEFAULT NULL,
  `effectiveGasPrice` varchar(78) DEFAULT NULL,
  `senderBalanceAfterRaw` varchar(78) DEFAULT NULL,
  `recipientBalanceAfterRaw` varchar(78) DEFAULT NULL,
  `senderFrozenAfterRaw` varchar(78) DEFAULT NULL,
  `verifiedAt` datetime(3) DEFAULT NULL,
  `errorCode` varchar(100) DEFAULT NULL,
  `errorMessage` varchar(2000) DEFAULT NULL,
  `syncStatus` enum('IDLE','QUEUED','PROCESSING','FAILED') NOT NULL DEFAULT 'IDLE',
  `syncRequestedAt` datetime(3) DEFAULT NULL,
  `syncStartedAt` datetime(3) DEFAULT NULL,
  `syncCompletedAt` datetime(3) DEFAULT NULL,
  `syncAttempts` int(10) unsigned NOT NULL DEFAULT 0,
  `nextSyncAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`transferUid`),
  UNIQUE KEY `ukTokenTransferIdempotency` (`senderUserUid`,`idempotencyKey`),
  UNIQUE KEY `ukTokenTransferActiveSenderToken` (`activeSenderTokenKey`),
  UNIQUE KEY `ukTokenTransferTxHash` (`txHash`),
  KEY `idxTokenTransferSenderHistory` (`senderUserUid`,`tokenUid`,`createdAt`),
  KEY `idxTokenTransferRecipientHistory` (`recipientUserUid`,`tokenUid`,`createdAt`),
  KEY `idxTokenTransferRecovery` (`status`,`syncStatus`,`nextSyncAt`,`isDeleted`,`createdAt`),
  KEY `idxTokenTransferExpiration` (`status`,`txHash`,`expiresAt`,`isDeleted`),
  KEY `idxTokenTransferMatch` (`chainId`,`tokenAddress`,`senderWalletAddress`,`recipientWalletAddress`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tokenTransferBlockchainEvent` (
  `transferEventUid` char(36) NOT NULL,
  `chainId` bigint(20) unsigned NOT NULL,
  `tokenAddress` varchar(42) NOT NULL,
  `fromWalletAddress` varchar(42) NOT NULL,
  `toWalletAddress` varchar(42) NOT NULL,
  `amountRaw` varchar(78) NOT NULL,
  `txHash` varchar(66) NOT NULL,
  `blockNumber` bigint(20) unsigned NOT NULL,
  `blockHash` varchar(66) DEFAULT NULL,
  `transactionIndex` int(10) unsigned NOT NULL,
  `logIndex` int(10) unsigned NOT NULL,
  `processingStatus` enum('NEW','MATCHED','UNMATCHED','FAILED') NOT NULL DEFAULT 'NEW',
  `matchedTransferUid` char(36) DEFAULT NULL,
  `processingAttempts` int(10) unsigned NOT NULL DEFAULT 0,
  `processingMessage` varchar(2000) DEFAULT NULL,
  `processedAt` datetime(3) DEFAULT NULL,
  `isCanonical` tinyint(1) NOT NULL DEFAULT 1,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`transferEventUid`),
  UNIQUE KEY `ukTokenTransferBlockchainEvent` (`chainId`,`txHash`,`logIndex`),
  KEY `idxTokenTransferEventProcess` (`chainId`,`processingStatus`,`isCanonical`,`blockNumber`),
  KEY `idxTokenTransferEventMatch` (`tokenAddress`,`fromWalletAddress`,`toWalletAddress`,`amountRaw`,`blockNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tokenTransferTransaction` (
  `transferTransactionUid` char(36) NOT NULL,
  `transferUid` char(36) NOT NULL,
  `txHash` varchar(66) NOT NULL,
  `status` enum('RECEIVED','PENDING','CONFIRMED','FAILED') NOT NULL,
  `blockNumber` bigint(20) unsigned DEFAULT NULL,
  `blockHash` varchar(66) DEFAULT NULL,
  `transactionIndex` int(10) unsigned DEFAULT NULL,
  `logIndex` int(10) unsigned DEFAULT NULL,
  `gasUsed` varchar(78) DEFAULT NULL,
  `effectiveGasPrice` varchar(78) DEFAULT NULL,
  `errorCode` varchar(100) DEFAULT NULL,
  `errorMessage` varchar(2000) DEFAULT NULL,
  `confirmedAt` datetime(3) DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`transferTransactionUid`),
  UNIQUE KEY `ukTokenTransferTransactionHash` (`transferUid`,`txHash`),
  KEY `idxTokenTransferTransactionTransfer` (`transferUid`,`createdAt`),
  KEY `idxTokenTransferTransactionHash` (`txHash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `userMaster` (
  `userUid` char(36) NOT NULL,
  `roleUid` char(36) NOT NULL,
  `fullName` varchar(120) NOT NULL,
  `email` varchar(254) NOT NULL,
  `passwordHash` varchar(255) NOT NULL,
  `emailVerified` tinyint(1) NOT NULL DEFAULT 0,
  `emailVerifiedAt` datetime(3) DEFAULT NULL,
  `privyUserId` varchar(128) DEFAULT NULL,
  `privyWalletId` varchar(128) DEFAULT NULL,
  `privyWalletAddress` varchar(42) DEFAULT NULL,
  `privyLinkedAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `lastLoginAt` datetime(3) DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`userUid`),
  UNIQUE KEY `ukUserMasterEmail` (`email`),
  UNIQUE KEY `ukUserMasterPrivyUserId` (`privyUserId`),
  UNIQUE KEY `ukUserMasterPrivyWalletAddress` (`privyWalletAddress`),
  KEY `idxUserMasterRoleUid` (`roleUid`),
  KEY `idxUserMasterStatus` (`isActive`,`isDeleted`),
  KEY `idxUserMasterFullName` (`fullName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `userRole` (
  `roleUid` char(36) NOT NULL,
  `roleName` varchar(80) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `isSystem` tinyint(1) NOT NULL DEFAULT 0,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT utc_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`roleUid`),
  UNIQUE KEY `ukUserRoleRoleName` (`roleName`),
  KEY `idxUserRoleStatus` (`isActive`,`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Static reference and configuration seed data.
INSERT INTO `entityTypeMaster` (`entityTypeUid`, `entityTypeCode`, `entityTypeName`, `displayOrder`)
VALUES
  ('30000000-0000-4000-8000-000000000001', 'LLC', 'Limited Liability Company', 10),
  ('30000000-0000-4000-8000-000000000002', 'CORPORATION', 'Corporation', 20),
  ('30000000-0000-4000-8000-000000000003', 'PARTNERSHIP', 'Partnership', 30),
  ('30000000-0000-4000-8000-000000000004', 'FOUNDATION', 'Foundation', 40),
  ('30000000-0000-4000-8000-000000000005', 'OTHER', 'Other', 50)
ON DUPLICATE KEY UPDATE `entityTypeName` = VALUES(`entityTypeName`), `isActive` = TRUE, `isDeleted` = FALSE;

INSERT INTO `industryMaster` (`industryUid`, `industryCode`, `industryName`, `displayOrder`)
VALUES
  ('31000000-0000-4000-8000-000000000001', 'FINANCIAL_SERVICES', 'Financial Services', 10),
  ('31000000-0000-4000-8000-000000000002', 'TECHNOLOGY', 'Technology', 20),
  ('31000000-0000-4000-8000-000000000003', 'REAL_ESTATE', 'Real Estate', 30),
  ('31000000-0000-4000-8000-000000000004', 'ENERGY', 'Energy', 40),
  ('31000000-0000-4000-8000-000000000005', 'HEALTHCARE', 'Healthcare', 50),
  ('31000000-0000-4000-8000-000000000006', 'OTHER', 'Other', 60)
ON DUPLICATE KEY UPDATE `industryName` = VALUES(`industryName`), `isActive` = TRUE, `isDeleted` = FALSE;

INSERT INTO `documentTypeMaster`
  (`documentTypeUid`, `documentTypeCode`, `documentTypeName`, `description`, `isRequired`, `displayOrder`)
VALUES
  ('32000000-0000-4000-8000-000000000001', 'CERTIFICATE_OF_INCORPORATION', 'Certificate of Incorporation', 'Official incorporation or formation certificate.', TRUE, 10),
  ('32000000-0000-4000-8000-000000000002', 'ARTICLES_OF_ASSOCIATION', 'Articles of Association', 'Articles, memorandum, bylaws, or equivalent constitutional document.', TRUE, 20),
  ('32000000-0000-4000-8000-000000000003', 'TAX_REGISTRATION', 'Tax Registration Certificate', 'Government-issued tax registration evidence.', TRUE, 30),
  ('32000000-0000-4000-8000-000000000004', 'OWNERSHIP_STRUCTURE', 'Ownership Structure', 'Current shareholder register or ownership chart.', TRUE, 40),
  ('32000000-0000-4000-8000-000000000005', 'PROOF_OF_ADDRESS', 'Proof of Registered Address', 'Recent proof of registered business address.', FALSE, 50),
  ('32000000-0000-4000-8000-000000000006', 'BUSINESS_LICENSE', 'Business License', 'Applicable regulatory or operating license.', FALSE, 60),
  ('32000000-0000-4000-8000-000000000007', 'OTHER', 'Other Supporting Document', 'Additional supporting documentation.', FALSE, 70)
ON DUPLICATE KEY UPDATE `documentTypeName` = VALUES(`documentTypeName`), `description` = VALUES(`description`), `isRequired` = VALUES(`isRequired`), `isActive` = TRUE, `isDeleted` = FALSE;

INSERT INTO `userRole` (`roleUid`, `roleName`, `description`, `isSystem`, `isActive`)
VALUES
  ('00000000-0000-4000-8000-000000000001', 'Super Administrator', 'Unrestricted platform administration role.', TRUE, TRUE),
  ('00000000-0000-4000-8000-000000000002', 'User', 'Legacy general user role retained for managed accounts.', TRUE, TRUE),
  ('00000000-0000-4000-8000-000000000003', 'Issuer', 'Capital Market issuer account created when signup isIssuer is true.', TRUE, TRUE),
  ('00000000-0000-4000-8000-000000000004', 'Investor', 'Capital Market investor account created when signup isIssuer is false.', TRUE, TRUE)
ON DUPLICATE KEY UPDATE `description` = VALUES(`description`), `isActive` = TRUE;

INSERT INTO `menuMaster` (`menuUid`, `menuName`, `menuCode`, `routePath`, `icon`, `displayOrder`)
VALUES
  ('10000000-0000-4000-8000-000000000001', 'Users', 'USERS', '/users', 'users', 10),
  ('10000000-0000-4000-8000-000000000002', 'Roles', 'ROLES', '/roles', 'shield', 20),
  ('10000000-0000-4000-8000-000000000003', 'Menus', 'MENUS', '/menus', 'menu', 30),
  ('10000000-0000-4000-8000-000000000004', 'Permissions', 'PERMISSIONS', '/permissions', 'key', 40),
  ('10000000-0000-4000-8000-000000000005', 'Settings', 'GENERAL_SETTINGS', '/settings', 'settings', 50),
  ('10000000-0000-4000-8000-000000000006', 'Organization Onboarding', 'ORGANIZATION_ONBOARDING', '/organization', 'building', 60),
  ('10000000-0000-4000-8000-000000000007', 'Token Creation', 'TOKEN_CREATION', '/token', 'coins', 70)
ON DUPLICATE KEY UPDATE `menuName` = VALUES(`menuName`), `routePath` = VALUES(`routePath`), `isActive` = TRUE;

-- API-level permissions for the system administrator. Paths intentionally match Express route templates.
INSERT INTO `permissionMaster`
  (`permissionUid`, `roleUid`, `menuUid`, `permissionName`, `permissionCode`, `httpMethod`, `apiPath`)
VALUES
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000001', 'Create user', 'USER_CREATE', 'POST', '/api/v1/users'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000001', 'List users', 'USER_LIST', 'GET', '/api/v1/users'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000001', 'View user', 'USER_VIEW', 'GET', '/api/v1/users/:userUid'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000001', 'Update user', 'USER_UPDATE', 'PUT', '/api/v1/users/:userUid'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000001', 'Delete user', 'USER_DELETE', 'DELETE', '/api/v1/users/:userUid'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000002', 'Create role', 'ROLE_CREATE', 'POST', '/api/v1/roles'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000002', 'List roles', 'ROLE_LIST', 'GET', '/api/v1/roles'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000002', 'View role', 'ROLE_VIEW', 'GET', '/api/v1/roles/:roleUid'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000002', 'Update role', 'ROLE_UPDATE', 'PUT', '/api/v1/roles/:roleUid'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000002', 'Delete role', 'ROLE_DELETE', 'DELETE', '/api/v1/roles/:roleUid'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000003', 'Create menu', 'MENU_CREATE', 'POST', '/api/v1/menus'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000003', 'List menus', 'MENU_LIST', 'GET', '/api/v1/menus'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000003', 'View menu', 'MENU_VIEW', 'GET', '/api/v1/menus/:menuUid'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000003', 'Update menu', 'MENU_UPDATE', 'PUT', '/api/v1/menus/:menuUid'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000003', 'Delete menu', 'MENU_DELETE', 'DELETE', '/api/v1/menus/:menuUid'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000004', 'Create permission', 'PERMISSION_CREATE', 'POST', '/api/v1/permissions'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000004', 'List permissions', 'PERMISSION_LIST', 'GET', '/api/v1/permissions'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000004', 'View permission', 'PERMISSION_VIEW', 'GET', '/api/v1/permissions/:permissionUid'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000004', 'Update permission', 'PERMISSION_UPDATE', 'PUT', '/api/v1/permissions/:permissionUid'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000004', 'Delete permission', 'PERMISSION_DELETE', 'DELETE', '/api/v1/permissions/:permissionUid'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000005', 'Create setting', 'SETTING_CREATE', 'POST', '/api/v1/general-settings'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000005', 'List settings', 'SETTING_LIST', 'GET', '/api/v1/general-settings'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000005', 'View setting', 'SETTING_VIEW', 'GET', '/api/v1/general-settings/:settingUid'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000005', 'Update setting', 'SETTING_UPDATE', 'PUT', '/api/v1/general-settings/:settingUid'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000005', 'Delete setting', 'SETTING_DELETE', 'DELETE', '/api/v1/general-settings/:settingUid'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000003', 'List menus', 'MENU_LIST', 'GET', '/api/v1/menus'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000003', 'View menu', 'MENU_VIEW', 'GET', '/api/v1/menus/:menuUid'),
  (UUID(), '00000000-0000-4000-8000-000000000004', '10000000-0000-4000-8000-000000000003', 'List menus', 'MENU_LIST', 'GET', '/api/v1/menus'),
  (UUID(), '00000000-0000-4000-8000-000000000004', '10000000-0000-4000-8000-000000000003', 'View menu', 'MENU_VIEW', 'GET', '/api/v1/menus/:menuUid'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000006', 'View own organization', 'ORG_VIEW_OWN', 'GET', '/api/v1/organizations/me'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000006', 'Save company information', 'ORG_SAVE_COMPANY', 'PUT', '/api/v1/organizations/me/company-information'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000006', 'Save jurisdiction', 'ORG_SAVE_JURISDICTION', 'PUT', '/api/v1/organizations/me/jurisdiction'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000006', 'Save beneficial owners', 'ORG_SAVE_UBOS', 'PUT', '/api/v1/organizations/me/beneficial-owners'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000006', 'Upload organization documents', 'ORG_UPLOAD_DOCUMENT', 'POST', '/api/v1/organizations/me/documents'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000006', 'List organization documents', 'ORG_LIST_DOCUMENTS', 'GET', '/api/v1/organizations/me/documents'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000006', 'Download organization document', 'ORG_DOWNLOAD_DOCUMENT', 'GET', '/api/v1/organizations/me/documents/:documentUid/download'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000006', 'Delete organization document', 'ORG_DELETE_DOCUMENT', 'DELETE', '/api/v1/organizations/me/documents/:documentUid'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000006', 'Submit organization', 'ORG_SUBMIT', 'POST', '/api/v1/organizations/me/submit'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000006', 'Mark organization user notified', 'ORG_MARK_USER_NOTIFIED', 'PATCH', '/api/v1/organizations/me/user-notified'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000006', 'List submitted organizations', 'ADMIN_ORG_LIST', 'GET', '/api/v1/admin/organizations'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000006', 'View submitted organization', 'ADMIN_ORG_VIEW', 'GET', '/api/v1/admin/organizations/:organizationUid'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000006', 'Preview or download organization document', 'ADMIN_ORG_DOCUMENT_FILE', 'GET', '/api/v1/admin/organizations/:organizationUid/documents/:documentUid/file'),
  (UUID(), '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000006', 'Review submitted organization', 'ADMIN_ORG_REVIEW', 'PATCH', '/api/v1/admin/organizations/:organizationUid/status')
ON DUPLICATE KEY UPDATE `permissionName` = VALUES(`permissionName`), `menuUid` = VALUES(`menuUid`), `isAllowed` = TRUE, `isActive` = TRUE, `isDeleted` = FALSE;

INSERT INTO `claimTopicMaster`
  (`claimTopicUid`, `claimTopicCode`, `claimTopicName`, `description`, `value`, `displayOrder`)
VALUES
  ('30000000-0000-4000-8000-000000000001', 'KYC', 'KYC (Know Your Customer)', 'Verified identity and residential address.', 1, 10),
  ('30000000-0000-4000-8000-000000000002', 'ACCREDITED_INVESTOR', 'Accredited Investor', 'Meets configured net-worth or income requirements.', 2, 20)
ON DUPLICATE KEY UPDATE
  `claimTopicName` = VALUES(`claimTopicName`),
  `description` = VALUES(`description`),
  `value` = VALUES(`value`),
  `displayOrder` = VALUES(`displayOrder`),
  `isActive` = TRUE,
  `isDeleted` = FALSE;

INSERT INTO `permissionMaster`
  (`permissionUid`, `roleUid`, `menuUid`, `permissionName`, `permissionCode`, `httpMethod`, `apiPath`)
VALUES
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000007', 'View own token form', 'TOKEN_VIEW_OWN', 'GET', '/api/v1/tokens/me'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000007', 'Save token information', 'TOKEN_SAVE_INFORMATION', 'PUT', '/api/v1/tokens/me/information'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000007', 'View token image', 'TOKEN_VIEW_IMAGE', 'GET', '/api/v1/tokens/me/image'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000007', 'Save token claims', 'TOKEN_SAVE_CLAIMS', 'PUT', '/api/v1/tokens/me/claims'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000007', 'Save token compliance rules', 'TOKEN_SAVE_COMPLIANCE', 'PUT', '/api/v1/tokens/me/compliance'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000007', 'Save token governance roles', 'TOKEN_SAVE_GOVERNANCE', 'PUT', '/api/v1/tokens/me/governance'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000007', 'Update current token price', 'TOKEN_UPDATE_CURRENT_PRICE', 'PATCH', '/api/v1/tokens/me/price'),
  (UUID(), '00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000007', 'Submit token for deployment', 'TOKEN_SUBMIT', 'POST', '/api/v1/tokens/me/submit')
ON DUPLICATE KEY UPDATE
  `permissionName` = VALUES(`permissionName`),
  `menuUid` = VALUES(`menuUid`),
  `isAllowed` = TRUE,
  `isActive` = TRUE,
  `isDeleted` = FALSE;

INSERT INTO `generalSettings`
  (`settingUid`, `settingKey`, `settingValue`, `valueType`, `settingGroup`, `description`, `isPublic`)
VALUES
  ('20000000-0000-4000-8000-000000000001', 'application.displayName', 'T-REX Capital Market', 'string', 'application', 'Public application display name.', TRUE),
  ('20000000-0000-4000-8000-000000000002', 'application.maintenanceMode', 'false', 'boolean', 'application', 'Whether the frontend should display maintenance mode.', TRUE),
  ('20000000-0000-4000-8000-000000000003', 'security.supportEmail', 'support@example.com', 'string', 'security', 'Public support contact address.', TRUE)
ON DUPLICATE KEY UPDATE `settingValue` = VALUES(`settingValue`), `description` = VALUES(`description`);
