/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as implementation from "./implementation";
export type { implementation };
import type * as interface from "./interface";
export type { interface };
