/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as modules from "./modules";
export type { modules };
import type * as platform from "./platform";
export type { platform };
